/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { CreditoCarbonoToken__factory } from './CreditoCarbonoToken__factory.js';
export { IRegistroProjetosCarbonoCredito__factory } from './IRegistroProjetosCarbonoCredito__factory.js';