/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IRegistroProjetosCarbonoCredito, IRegistroProjetosCarbonoCreditoInterface } from "../../CreditoCarbonoToken.sol/IRegistroProjetosCarbonoCredito.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "idProjeto",
        "type": "uint256"
      }
    ],
    "name": "marcarCreditosEmitidos",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "idProjeto",
        "type": "uint256"
      }
    ],
    "name": "obterCreditosAprovados",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "idProjeto",
        "type": "uint256"
      }
    ],
    "name": "obterProponente",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "idProjeto",
        "type": "uint256"
      }
    ],
    "name": "projetoAprovado",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "idProjeto",
        "type": "uint256"
      }
    ],
    "name": "projetoEmitido",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class IRegistroProjetosCarbonoCredito__factory {
    static readonly abi = _abi;
    static createInterface(): IRegistroProjetosCarbonoCreditoInterface {
      return new Interface(_abi) as IRegistroProjetosCarbonoCreditoInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IRegistroProjetosCarbonoCredito {
      return new Contract(address, _abi, runner) as unknown as IRegistroProjetosCarbonoCredito;
    }
  }
  