/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface GovernancaCarbonoInterface extends Interface {
    getFunction(nameOrSignature: "alterarParametrosGovernanca" | "atualizarTokenGovernanca" | "cancelarProposta" | "criarProposta" | "estadoProposta" | "executarProposta" | "jaVotou" | "owner" | "pesoDoVoto" | "prazoVotacaoPadrao" | "propostaAprovada" | "propostas" | "quorumMinimo" | "renounceOwnership" | "saldoMinimoParaPropor" | "tokenImpactoCarbono" | "totalPropostas" | "totalVotos" | "transferOwnership" | "votar" | "votoFavoravel"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "OwnershipTransferred" | "ParametrosGovernancaAlterados" | "PropostaCancelada" | "PropostaCriada" | "PropostaExecutada" | "TokenGovernancaAtualizado" | "VotoRegistrado"): EventFragment;

    encodeFunctionData(functionFragment: 'alterarParametrosGovernanca', values: [BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'atualizarTokenGovernanca', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'cancelarProposta', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'criarProposta', values: [AddressLike, BigNumberish, BytesLike, string]): string;
encodeFunctionData(functionFragment: 'estadoProposta', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'executarProposta', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'jaVotou', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'pesoDoVoto', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'prazoVotacaoPadrao', values?: undefined): string;
encodeFunctionData(functionFragment: 'propostaAprovada', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'propostas', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'quorumMinimo', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'saldoMinimoParaPropor', values?: undefined): string;
encodeFunctionData(functionFragment: 'tokenImpactoCarbono', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalPropostas', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalVotos', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'votar', values: [BigNumberish, boolean]): string;
encodeFunctionData(functionFragment: 'votoFavoravel', values: [BigNumberish, AddressLike]): string;

    decodeFunctionResult(functionFragment: 'alterarParametrosGovernanca', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'atualizarTokenGovernanca', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cancelarProposta', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'criarProposta', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'estadoProposta', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'executarProposta', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'jaVotou', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pesoDoVoto', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'prazoVotacaoPadrao', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'propostaAprovada', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'propostas', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'quorumMinimo', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'saldoMinimoParaPropor', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tokenImpactoCarbono', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalPropostas', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalVotos', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'votar', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'votoFavoravel', data: BytesLike): Result;
  }

  
    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ParametrosGovernancaAlteradosEvent {
      export type InputTuple = [prazoVotacaoPadrao: BigNumberish, quorumMinimo: BigNumberish, saldoMinimoParaPropor: BigNumberish];
      export type OutputTuple = [prazoVotacaoPadrao: bigint, quorumMinimo: bigint, saldoMinimoParaPropor: bigint];
      export interface OutputObject {prazoVotacaoPadrao: bigint, quorumMinimo: bigint, saldoMinimoParaPropor: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PropostaCanceladaEvent {
      export type InputTuple = [idProposta: BigNumberish, cancelador: AddressLike];
      export type OutputTuple = [idProposta: bigint, cancelador: string];
      export interface OutputObject {idProposta: bigint, cancelador: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PropostaCriadaEvent {
      export type InputTuple = [idProposta: BigNumberish, proponente: AddressLike, contratoAlvo: AddressLike, descricao: string, inicioVotacao: BigNumberish, fimVotacao: BigNumberish];
      export type OutputTuple = [idProposta: bigint, proponente: string, contratoAlvo: string, descricao: string, inicioVotacao: bigint, fimVotacao: bigint];
      export interface OutputObject {idProposta: bigint, proponente: string, contratoAlvo: string, descricao: string, inicioVotacao: bigint, fimVotacao: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PropostaExecutadaEvent {
      export type InputTuple = [idProposta: BigNumberish, executor: AddressLike, sucesso: boolean];
      export type OutputTuple = [idProposta: bigint, executor: string, sucesso: boolean];
      export interface OutputObject {idProposta: bigint, executor: string, sucesso: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TokenGovernancaAtualizadoEvent {
      export type InputTuple = [novoToken: AddressLike];
      export type OutputTuple = [novoToken: string];
      export interface OutputObject {novoToken: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace VotoRegistradoEvent {
      export type InputTuple = [idProposta: BigNumberish, votante: AddressLike, apoio: boolean, peso: BigNumberish];
      export type OutputTuple = [idProposta: bigint, votante: string, apoio: boolean, peso: bigint];
      export interface OutputObject {idProposta: bigint, votante: string, apoio: boolean, peso: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface GovernancaCarbono extends BaseContract {
    
    connect(runner?: ContractRunner | null): GovernancaCarbono;
    waitForDeployment(): Promise<this>;

    interface: GovernancaCarbonoInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    alterarParametrosGovernanca: TypedContractMethod<
      [novoPrazoVotacaoPadrao: BigNumberish, novoQuorumMinimo: BigNumberish, novoSaldoMinimoParaPropor: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    atualizarTokenGovernanca: TypedContractMethod<
      [novoToken: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    cancelarProposta: TypedContractMethod<
      [idProposta: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    criarProposta: TypedContractMethod<
      [contratoAlvo: AddressLike, valorETH: BigNumberish, dadosExecucao: BytesLike, descricao: string, ],
      [bigint],
      'nonpayable'
    >
    

    
    estadoProposta: TypedContractMethod<
      [idProposta: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    executarProposta: TypedContractMethod<
      [idProposta: BigNumberish, ],
      [string],
      'nonpayable'
    >
    

    
    jaVotou: TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    pesoDoVoto: TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    prazoVotacaoPadrao: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    propostaAprovada: TypedContractMethod<
      [idProposta: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    propostas: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, bigint, string, string, bigint, bigint, bigint, bigint, boolean, boolean] & {idProposta: bigint, proponente: string, contratoAlvo: string, valorETH: bigint, dadosExecucao: string, descricao: string, inicioVotacao: bigint, fimVotacao: bigint, votosFavor: bigint, votosContra: bigint, executada: boolean, cancelada: boolean }],
      'view'
    >
    

    
    quorumMinimo: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    saldoMinimoParaPropor: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    tokenImpactoCarbono: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    totalPropostas: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    totalVotos: TypedContractMethod<
      [idProposta: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    votar: TypedContractMethod<
      [idProposta: BigNumberish, apoio: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    votoFavoravel: TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [boolean],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'alterarParametrosGovernanca'): TypedContractMethod<
      [novoPrazoVotacaoPadrao: BigNumberish, novoQuorumMinimo: BigNumberish, novoSaldoMinimoParaPropor: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'atualizarTokenGovernanca'): TypedContractMethod<
      [novoToken: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'cancelarProposta'): TypedContractMethod<
      [idProposta: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'criarProposta'): TypedContractMethod<
      [contratoAlvo: AddressLike, valorETH: BigNumberish, dadosExecucao: BytesLike, descricao: string, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'estadoProposta'): TypedContractMethod<
      [idProposta: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'executarProposta'): TypedContractMethod<
      [idProposta: BigNumberish, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'jaVotou'): TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'pesoDoVoto'): TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'prazoVotacaoPadrao'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'propostaAprovada'): TypedContractMethod<
      [idProposta: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'propostas'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, bigint, string, string, bigint, bigint, bigint, bigint, boolean, boolean] & {idProposta: bigint, proponente: string, contratoAlvo: string, valorETH: bigint, dadosExecucao: string, descricao: string, inicioVotacao: bigint, fimVotacao: bigint, votosFavor: bigint, votosContra: bigint, executada: boolean, cancelada: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'quorumMinimo'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'saldoMinimoParaPropor'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'tokenImpactoCarbono'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'totalPropostas'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalVotos'): TypedContractMethod<
      [idProposta: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'votar'): TypedContractMethod<
      [idProposta: BigNumberish, apoio: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'votoFavoravel'): TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [boolean],
      'view'
    >;

    getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'ParametrosGovernancaAlterados'): TypedContractEvent<ParametrosGovernancaAlteradosEvent.InputTuple, ParametrosGovernancaAlteradosEvent.OutputTuple, ParametrosGovernancaAlteradosEvent.OutputObject>;
getEvent(key: 'PropostaCancelada'): TypedContractEvent<PropostaCanceladaEvent.InputTuple, PropostaCanceladaEvent.OutputTuple, PropostaCanceladaEvent.OutputObject>;
getEvent(key: 'PropostaCriada'): TypedContractEvent<PropostaCriadaEvent.InputTuple, PropostaCriadaEvent.OutputTuple, PropostaCriadaEvent.OutputObject>;
getEvent(key: 'PropostaExecutada'): TypedContractEvent<PropostaExecutadaEvent.InputTuple, PropostaExecutadaEvent.OutputTuple, PropostaExecutadaEvent.OutputObject>;
getEvent(key: 'TokenGovernancaAtualizado'): TypedContractEvent<TokenGovernancaAtualizadoEvent.InputTuple, TokenGovernancaAtualizadoEvent.OutputTuple, TokenGovernancaAtualizadoEvent.OutputObject>;
getEvent(key: 'VotoRegistrado'): TypedContractEvent<VotoRegistradoEvent.InputTuple, VotoRegistradoEvent.OutputTuple, VotoRegistradoEvent.OutputObject>;

    filters: {
      
      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'ParametrosGovernancaAlterados(uint256,uint256,uint256)': TypedContractEvent<ParametrosGovernancaAlteradosEvent.InputTuple, ParametrosGovernancaAlteradosEvent.OutputTuple, ParametrosGovernancaAlteradosEvent.OutputObject>;
      ParametrosGovernancaAlterados: TypedContractEvent<ParametrosGovernancaAlteradosEvent.InputTuple, ParametrosGovernancaAlteradosEvent.OutputTuple, ParametrosGovernancaAlteradosEvent.OutputObject>;
    

      'PropostaCancelada(uint256,address)': TypedContractEvent<PropostaCanceladaEvent.InputTuple, PropostaCanceladaEvent.OutputTuple, PropostaCanceladaEvent.OutputObject>;
      PropostaCancelada: TypedContractEvent<PropostaCanceladaEvent.InputTuple, PropostaCanceladaEvent.OutputTuple, PropostaCanceladaEvent.OutputObject>;
    

      'PropostaCriada(uint256,address,address,string,uint256,uint256)': TypedContractEvent<PropostaCriadaEvent.InputTuple, PropostaCriadaEvent.OutputTuple, PropostaCriadaEvent.OutputObject>;
      PropostaCriada: TypedContractEvent<PropostaCriadaEvent.InputTuple, PropostaCriadaEvent.OutputTuple, PropostaCriadaEvent.OutputObject>;
    

      'PropostaExecutada(uint256,address,bool)': TypedContractEvent<PropostaExecutadaEvent.InputTuple, PropostaExecutadaEvent.OutputTuple, PropostaExecutadaEvent.OutputObject>;
      PropostaExecutada: TypedContractEvent<PropostaExecutadaEvent.InputTuple, PropostaExecutadaEvent.OutputTuple, PropostaExecutadaEvent.OutputObject>;
    

      'TokenGovernancaAtualizado(address)': TypedContractEvent<TokenGovernancaAtualizadoEvent.InputTuple, TokenGovernancaAtualizadoEvent.OutputTuple, TokenGovernancaAtualizadoEvent.OutputObject>;
      TokenGovernancaAtualizado: TypedContractEvent<TokenGovernancaAtualizadoEvent.InputTuple, TokenGovernancaAtualizadoEvent.OutputTuple, TokenGovernancaAtualizadoEvent.OutputObject>;
    

      'VotoRegistrado(uint256,address,bool,uint256)': TypedContractEvent<VotoRegistradoEvent.InputTuple, VotoRegistradoEvent.OutputTuple, VotoRegistradoEvent.OutputObject>;
      VotoRegistrado: TypedContractEvent<VotoRegistradoEvent.InputTuple, VotoRegistradoEvent.OutputTuple, VotoRegistradoEvent.OutputObject>;
    
    };
  }