/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'AdaptadorOraculoChainlink', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.AdaptadorOraculoChainlink__factory>
getContractFactory(name: 'AggregatorV3Interface', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.AggregatorV3Interface__factory>
getContractFactory(name: 'CreditoCarbonoToken', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.CreditoCarbonoToken__factory>
getContractFactory(name: 'IRegistroProjetosCarbonoCredito', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IRegistroProjetosCarbonoCredito__factory>
getContractFactory(name: 'CertificadoCompensacaoNFT', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.CertificadoCompensacaoNFT__factory>
getContractFactory(name: 'GovernancaCarbono', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.GovernancaCarbono__factory>
getContractFactory(name: 'ICreditoCarbonoTokenMercado', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ICreditoCarbonoTokenMercado__factory>
getContractFactory(name: 'IRegistroOrganizacoesMercado', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IRegistroOrganizacoesMercado__factory>
getContractFactory(name: 'ITesourariaCarbonoMercado', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ITesourariaCarbonoMercado__factory>
getContractFactory(name: 'MercadoCarbono', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MercadoCarbono__factory>
getContractFactory(name: 'ICertificadoCompensacaoNFTAposentadoria', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ICertificadoCompensacaoNFTAposentadoria__factory>
getContractFactory(name: 'ICreditoCarbonoTokenAposentadoria', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ICreditoCarbonoTokenAposentadoria__factory>
getContractFactory(name: 'IRegistroOrganizacoesAposentadoria', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IRegistroOrganizacoesAposentadoria__factory>
getContractFactory(name: 'ITesourariaCarbonoAposentadoria', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ITesourariaCarbonoAposentadoria__factory>
getContractFactory(name: 'RegistroAposentadorias', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.RegistroAposentadorias__factory>
getContractFactory(name: 'RegistroOrganizacoes', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.RegistroOrganizacoes__factory>
getContractFactory(name: 'IRegistroOrganizacoes', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IRegistroOrganizacoes__factory>
getContractFactory(name: 'ITesourariaCarbono', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ITesourariaCarbono__factory>
getContractFactory(name: 'RegistroProjetosCarbono', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.RegistroProjetosCarbono__factory>
getContractFactory(name: 'TesourariaCarbono', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.TesourariaCarbono__factory>
getContractFactory(name: 'ITesourariaCarbonoStaking', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ITesourariaCarbonoStaking__factory>
getContractFactory(name: 'StakingCarbono', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.StakingCarbono__factory>
getContractFactory(name: 'TokenImpactoCarbono', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.TokenImpactoCarbono__factory>
getContractFactory(name: 'IRegistroOrganizacoesValidacao', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IRegistroOrganizacoesValidacao__factory>
getContractFactory(name: 'IRegistroProjetosCarbonoValidacao', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IRegistroProjetosCarbonoValidacao__factory>
getContractFactory(name: 'IStakingCarbonoValidacao', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IStakingCarbonoValidacao__factory>
getContractFactory(name: 'ValidacaoProjetos', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ValidacaoProjetos__factory>
getContractFactory(name: 'MockPriceFeedChainlink', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockPriceFeedChainlink__factory>

  getContractAt(name: 'AdaptadorOraculoChainlink', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.AdaptadorOraculoChainlink>
getContractAt(name: 'AggregatorV3Interface', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.AggregatorV3Interface>
getContractAt(name: 'CreditoCarbonoToken', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.CreditoCarbonoToken>
getContractAt(name: 'IRegistroProjetosCarbonoCredito', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IRegistroProjetosCarbonoCredito>
getContractAt(name: 'CertificadoCompensacaoNFT', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.CertificadoCompensacaoNFT>
getContractAt(name: 'GovernancaCarbono', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.GovernancaCarbono>
getContractAt(name: 'ICreditoCarbonoTokenMercado', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ICreditoCarbonoTokenMercado>
getContractAt(name: 'IRegistroOrganizacoesMercado', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IRegistroOrganizacoesMercado>
getContractAt(name: 'ITesourariaCarbonoMercado', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ITesourariaCarbonoMercado>
getContractAt(name: 'MercadoCarbono', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MercadoCarbono>
getContractAt(name: 'ICertificadoCompensacaoNFTAposentadoria', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ICertificadoCompensacaoNFTAposentadoria>
getContractAt(name: 'ICreditoCarbonoTokenAposentadoria', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ICreditoCarbonoTokenAposentadoria>
getContractAt(name: 'IRegistroOrganizacoesAposentadoria', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IRegistroOrganizacoesAposentadoria>
getContractAt(name: 'ITesourariaCarbonoAposentadoria', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ITesourariaCarbonoAposentadoria>
getContractAt(name: 'RegistroAposentadorias', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.RegistroAposentadorias>
getContractAt(name: 'RegistroOrganizacoes', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.RegistroOrganizacoes>
getContractAt(name: 'IRegistroOrganizacoes', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IRegistroOrganizacoes>
getContractAt(name: 'ITesourariaCarbono', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ITesourariaCarbono>
getContractAt(name: 'RegistroProjetosCarbono', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.RegistroProjetosCarbono>
getContractAt(name: 'TesourariaCarbono', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.TesourariaCarbono>
getContractAt(name: 'ITesourariaCarbonoStaking', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ITesourariaCarbonoStaking>
getContractAt(name: 'StakingCarbono', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.StakingCarbono>
getContractAt(name: 'TokenImpactoCarbono', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.TokenImpactoCarbono>
getContractAt(name: 'IRegistroOrganizacoesValidacao', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IRegistroOrganizacoesValidacao>
getContractAt(name: 'IRegistroProjetosCarbonoValidacao', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IRegistroProjetosCarbonoValidacao>
getContractAt(name: 'IStakingCarbonoValidacao', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IStakingCarbonoValidacao>
getContractAt(name: 'ValidacaoProjetos', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ValidacaoProjetos>
getContractAt(name: 'MockPriceFeedChainlink', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockPriceFeedChainlink>

  deployContract(name: 'AdaptadorOraculoChainlink', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.AdaptadorOraculoChainlink>
deployContract(name: 'AggregatorV3Interface', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.AggregatorV3Interface>
deployContract(name: 'CreditoCarbonoToken', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.CreditoCarbonoToken>
deployContract(name: 'IRegistroProjetosCarbonoCredito', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IRegistroProjetosCarbonoCredito>
deployContract(name: 'CertificadoCompensacaoNFT', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.CertificadoCompensacaoNFT>
deployContract(name: 'GovernancaCarbono', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.GovernancaCarbono>
deployContract(name: 'ICreditoCarbonoTokenMercado', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ICreditoCarbonoTokenMercado>
deployContract(name: 'IRegistroOrganizacoesMercado', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IRegistroOrganizacoesMercado>
deployContract(name: 'ITesourariaCarbonoMercado', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ITesourariaCarbonoMercado>
deployContract(name: 'MercadoCarbono', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MercadoCarbono>
deployContract(name: 'ICertificadoCompensacaoNFTAposentadoria', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ICertificadoCompensacaoNFTAposentadoria>
deployContract(name: 'ICreditoCarbonoTokenAposentadoria', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ICreditoCarbonoTokenAposentadoria>
deployContract(name: 'IRegistroOrganizacoesAposentadoria', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IRegistroOrganizacoesAposentadoria>
deployContract(name: 'ITesourariaCarbonoAposentadoria', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ITesourariaCarbonoAposentadoria>
deployContract(name: 'RegistroAposentadorias', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.RegistroAposentadorias>
deployContract(name: 'RegistroOrganizacoes', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.RegistroOrganizacoes>
deployContract(name: 'IRegistroOrganizacoes', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IRegistroOrganizacoes>
deployContract(name: 'ITesourariaCarbono', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ITesourariaCarbono>
deployContract(name: 'RegistroProjetosCarbono', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.RegistroProjetosCarbono>
deployContract(name: 'TesourariaCarbono', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.TesourariaCarbono>
deployContract(name: 'ITesourariaCarbonoStaking', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ITesourariaCarbonoStaking>
deployContract(name: 'StakingCarbono', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.StakingCarbono>
deployContract(name: 'TokenImpactoCarbono', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.TokenImpactoCarbono>
deployContract(name: 'IRegistroOrganizacoesValidacao', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IRegistroOrganizacoesValidacao>
deployContract(name: 'IRegistroProjetosCarbonoValidacao', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IRegistroProjetosCarbonoValidacao>
deployContract(name: 'IStakingCarbonoValidacao', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IStakingCarbonoValidacao>
deployContract(name: 'ValidacaoProjetos', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ValidacaoProjetos>
deployContract(name: 'MockPriceFeedChainlink', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockPriceFeedChainlink>

  deployContract(name: 'AdaptadorOraculoChainlink', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.AdaptadorOraculoChainlink>
deployContract(name: 'AggregatorV3Interface', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.AggregatorV3Interface>
deployContract(name: 'CreditoCarbonoToken', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.CreditoCarbonoToken>
deployContract(name: 'IRegistroProjetosCarbonoCredito', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IRegistroProjetosCarbonoCredito>
deployContract(name: 'CertificadoCompensacaoNFT', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.CertificadoCompensacaoNFT>
deployContract(name: 'GovernancaCarbono', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.GovernancaCarbono>
deployContract(name: 'ICreditoCarbonoTokenMercado', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ICreditoCarbonoTokenMercado>
deployContract(name: 'IRegistroOrganizacoesMercado', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IRegistroOrganizacoesMercado>
deployContract(name: 'ITesourariaCarbonoMercado', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ITesourariaCarbonoMercado>
deployContract(name: 'MercadoCarbono', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MercadoCarbono>
deployContract(name: 'ICertificadoCompensacaoNFTAposentadoria', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ICertificadoCompensacaoNFTAposentadoria>
deployContract(name: 'ICreditoCarbonoTokenAposentadoria', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ICreditoCarbonoTokenAposentadoria>
deployContract(name: 'IRegistroOrganizacoesAposentadoria', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IRegistroOrganizacoesAposentadoria>
deployContract(name: 'ITesourariaCarbonoAposentadoria', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ITesourariaCarbonoAposentadoria>
deployContract(name: 'RegistroAposentadorias', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.RegistroAposentadorias>
deployContract(name: 'RegistroOrganizacoes', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.RegistroOrganizacoes>
deployContract(name: 'IRegistroOrganizacoes', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IRegistroOrganizacoes>
deployContract(name: 'ITesourariaCarbono', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ITesourariaCarbono>
deployContract(name: 'RegistroProjetosCarbono', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.RegistroProjetosCarbono>
deployContract(name: 'TesourariaCarbono', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.TesourariaCarbono>
deployContract(name: 'ITesourariaCarbonoStaking', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ITesourariaCarbonoStaking>
deployContract(name: 'StakingCarbono', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.StakingCarbono>
deployContract(name: 'TokenImpactoCarbono', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.TokenImpactoCarbono>
deployContract(name: 'IRegistroOrganizacoesValidacao', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IRegistroOrganizacoesValidacao>
deployContract(name: 'IRegistroProjetosCarbonoValidacao', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IRegistroProjetosCarbonoValidacao>
deployContract(name: 'IStakingCarbonoValidacao', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IStakingCarbonoValidacao>
deployContract(name: 'ValidacaoProjetos', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ValidacaoProjetos>
deployContract(name: 'MockPriceFeedChainlink', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockPriceFeedChainlink>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  