/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface TesourariaCarbonoInterface extends Interface {
    getFunction(nameOrSignature: "atualizarTokenImpactoCarbono" | "autorizarContrato" | "contratosAutorizados" | "depositarTIC" | "enviarETH" | "enviarETHAutorizado" | "enviarTIC" | "enviarTICAutorizado" | "owner" | "receberTaxaETH" | "renounceOwnership" | "saldoETH" | "saldoTIC" | "tokenImpactoCarbono" | "totalETHEnviado" | "totalETHRecebido" | "totalTICEnviado" | "totalTICRecebido" | "transferOwnership"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ContratoAutorizado" | "ETHEnviado" | "ETHRecebido" | "OwnershipTransferred" | "TICEnviado" | "TICRecebido" | "TokenImpactoCarbonoAtualizado"): EventFragment;

    encodeFunctionData(functionFragment: 'atualizarTokenImpactoCarbono', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'autorizarContrato', values: [AddressLike, boolean]): string;
encodeFunctionData(functionFragment: 'contratosAutorizados', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'depositarTIC', values: [BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'enviarETH', values: [AddressLike, BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'enviarETHAutorizado', values: [AddressLike, BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'enviarTIC', values: [AddressLike, BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'enviarTICAutorizado', values: [AddressLike, BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'receberTaxaETH', values: [string]): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'saldoETH', values?: undefined): string;
encodeFunctionData(functionFragment: 'saldoTIC', values?: undefined): string;
encodeFunctionData(functionFragment: 'tokenImpactoCarbono', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalETHEnviado', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalETHRecebido', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalTICEnviado', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalTICRecebido', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'atualizarTokenImpactoCarbono', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'autorizarContrato', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'contratosAutorizados', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'depositarTIC', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'enviarETH', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'enviarETHAutorizado', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'enviarTIC', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'enviarTICAutorizado', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'receberTaxaETH', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'saldoETH', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'saldoTIC', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tokenImpactoCarbono', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalETHEnviado', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalETHRecebido', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalTICEnviado', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalTICRecebido', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
  }

  
    export namespace ContratoAutorizadoEvent {
      export type InputTuple = [contrato: AddressLike, autorizado: boolean];
      export type OutputTuple = [contrato: string, autorizado: boolean];
      export interface OutputObject {contrato: string, autorizado: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ETHEnviadoEvent {
      export type InputTuple = [destinatario: AddressLike, valor: BigNumberish, finalidade: string];
      export type OutputTuple = [destinatario: string, valor: bigint, finalidade: string];
      export interface OutputObject {destinatario: string, valor: bigint, finalidade: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ETHRecebidoEvent {
      export type InputTuple = [remetente: AddressLike, valor: BigNumberish, origem: string];
      export type OutputTuple = [remetente: string, valor: bigint, origem: string];
      export interface OutputObject {remetente: string, valor: bigint, origem: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TICEnviadoEvent {
      export type InputTuple = [destinatario: AddressLike, quantidade: BigNumberish, finalidade: string];
      export type OutputTuple = [destinatario: string, quantidade: bigint, finalidade: string];
      export interface OutputObject {destinatario: string, quantidade: bigint, finalidade: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TICRecebidoEvent {
      export type InputTuple = [remetente: AddressLike, quantidade: BigNumberish, origem: string];
      export type OutputTuple = [remetente: string, quantidade: bigint, origem: string];
      export interface OutputObject {remetente: string, quantidade: bigint, origem: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TokenImpactoCarbonoAtualizadoEvent {
      export type InputTuple = [novoToken: AddressLike];
      export type OutputTuple = [novoToken: string];
      export interface OutputObject {novoToken: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface TesourariaCarbono extends BaseContract {
    
    connect(runner?: ContractRunner | null): TesourariaCarbono;
    waitForDeployment(): Promise<this>;

    interface: TesourariaCarbonoInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    atualizarTokenImpactoCarbono: TypedContractMethod<
      [novoToken: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    autorizarContrato: TypedContractMethod<
      [contrato: AddressLike, autorizado: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    contratosAutorizados: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    depositarTIC: TypedContractMethod<
      [quantidade: BigNumberish, origem: string, ],
      [void],
      'nonpayable'
    >
    

    
    enviarETH: TypedContractMethod<
      [destinatario: AddressLike, valor: BigNumberish, finalidade: string, ],
      [void],
      'nonpayable'
    >
    

    
    enviarETHAutorizado: TypedContractMethod<
      [destinatario: AddressLike, valor: BigNumberish, finalidade: string, ],
      [void],
      'nonpayable'
    >
    

    
    enviarTIC: TypedContractMethod<
      [destinatario: AddressLike, quantidade: BigNumberish, finalidade: string, ],
      [void],
      'nonpayable'
    >
    

    
    enviarTICAutorizado: TypedContractMethod<
      [destinatario: AddressLike, quantidade: BigNumberish, finalidade: string, ],
      [void],
      'nonpayable'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    receberTaxaETH: TypedContractMethod<
      [origem: string, ],
      [void],
      'payable'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    saldoETH: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    saldoTIC: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    tokenImpactoCarbono: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    totalETHEnviado: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    totalETHRecebido: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    totalTICEnviado: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    totalTICRecebido: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'atualizarTokenImpactoCarbono'): TypedContractMethod<
      [novoToken: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'autorizarContrato'): TypedContractMethod<
      [contrato: AddressLike, autorizado: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'contratosAutorizados'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'depositarTIC'): TypedContractMethod<
      [quantidade: BigNumberish, origem: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'enviarETH'): TypedContractMethod<
      [destinatario: AddressLike, valor: BigNumberish, finalidade: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'enviarETHAutorizado'): TypedContractMethod<
      [destinatario: AddressLike, valor: BigNumberish, finalidade: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'enviarTIC'): TypedContractMethod<
      [destinatario: AddressLike, quantidade: BigNumberish, finalidade: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'enviarTICAutorizado'): TypedContractMethod<
      [destinatario: AddressLike, quantidade: BigNumberish, finalidade: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'receberTaxaETH'): TypedContractMethod<
      [origem: string, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'saldoETH'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'saldoTIC'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'tokenImpactoCarbono'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'totalETHEnviado'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalETHRecebido'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalTICEnviado'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalTICRecebido'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'ContratoAutorizado'): TypedContractEvent<ContratoAutorizadoEvent.InputTuple, ContratoAutorizadoEvent.OutputTuple, ContratoAutorizadoEvent.OutputObject>;
getEvent(key: 'ETHEnviado'): TypedContractEvent<ETHEnviadoEvent.InputTuple, ETHEnviadoEvent.OutputTuple, ETHEnviadoEvent.OutputObject>;
getEvent(key: 'ETHRecebido'): TypedContractEvent<ETHRecebidoEvent.InputTuple, ETHRecebidoEvent.OutputTuple, ETHRecebidoEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'TICEnviado'): TypedContractEvent<TICEnviadoEvent.InputTuple, TICEnviadoEvent.OutputTuple, TICEnviadoEvent.OutputObject>;
getEvent(key: 'TICRecebido'): TypedContractEvent<TICRecebidoEvent.InputTuple, TICRecebidoEvent.OutputTuple, TICRecebidoEvent.OutputObject>;
getEvent(key: 'TokenImpactoCarbonoAtualizado'): TypedContractEvent<TokenImpactoCarbonoAtualizadoEvent.InputTuple, TokenImpactoCarbonoAtualizadoEvent.OutputTuple, TokenImpactoCarbonoAtualizadoEvent.OutputObject>;

    filters: {
      
      'ContratoAutorizado(address,bool)': TypedContractEvent<ContratoAutorizadoEvent.InputTuple, ContratoAutorizadoEvent.OutputTuple, ContratoAutorizadoEvent.OutputObject>;
      ContratoAutorizado: TypedContractEvent<ContratoAutorizadoEvent.InputTuple, ContratoAutorizadoEvent.OutputTuple, ContratoAutorizadoEvent.OutputObject>;
    

      'ETHEnviado(address,uint256,string)': TypedContractEvent<ETHEnviadoEvent.InputTuple, ETHEnviadoEvent.OutputTuple, ETHEnviadoEvent.OutputObject>;
      ETHEnviado: TypedContractEvent<ETHEnviadoEvent.InputTuple, ETHEnviadoEvent.OutputTuple, ETHEnviadoEvent.OutputObject>;
    

      'ETHRecebido(address,uint256,string)': TypedContractEvent<ETHRecebidoEvent.InputTuple, ETHRecebidoEvent.OutputTuple, ETHRecebidoEvent.OutputObject>;
      ETHRecebido: TypedContractEvent<ETHRecebidoEvent.InputTuple, ETHRecebidoEvent.OutputTuple, ETHRecebidoEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'TICEnviado(address,uint256,string)': TypedContractEvent<TICEnviadoEvent.InputTuple, TICEnviadoEvent.OutputTuple, TICEnviadoEvent.OutputObject>;
      TICEnviado: TypedContractEvent<TICEnviadoEvent.InputTuple, TICEnviadoEvent.OutputTuple, TICEnviadoEvent.OutputObject>;
    

      'TICRecebido(address,uint256,string)': TypedContractEvent<TICRecebidoEvent.InputTuple, TICRecebidoEvent.OutputTuple, TICRecebidoEvent.OutputObject>;
      TICRecebido: TypedContractEvent<TICRecebidoEvent.InputTuple, TICRecebidoEvent.OutputTuple, TICRecebidoEvent.OutputObject>;
    

      'TokenImpactoCarbonoAtualizado(address)': TypedContractEvent<TokenImpactoCarbonoAtualizadoEvent.InputTuple, TokenImpactoCarbonoAtualizadoEvent.OutputTuple, TokenImpactoCarbonoAtualizadoEvent.OutputObject>;
      TokenImpactoCarbonoAtualizado: TypedContractEvent<TokenImpactoCarbonoAtualizadoEvent.InputTuple, TokenImpactoCarbonoAtualizadoEvent.OutputTuple, TokenImpactoCarbonoAtualizadoEvent.OutputObject>;
    
    };
  }