/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CreditoCarbonoToken } from './CreditoCarbonoToken.js';
export type { IRegistroProjetosCarbonoCredito } from './IRegistroProjetosCarbonoCredito.js';