/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface IRegistroProjetosCarbonoCreditoInterface extends Interface {
    getFunction(nameOrSignature: "marcarCreditosEmitidos" | "obterCreditosAprovados" | "obterProponente" | "projetoAprovado" | "projetoEmitido"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'marcarCreditosEmitidos', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'obterCreditosAprovados', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'obterProponente', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'projetoAprovado', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'projetoEmitido', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'marcarCreditosEmitidos', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'obterCreditosAprovados', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'obterProponente', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'projetoAprovado', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'projetoEmitido', data: BytesLike): Result;
  }

  

  export interface IRegistroProjetosCarbonoCredito extends BaseContract {
    
    connect(runner?: ContractRunner | null): IRegistroProjetosCarbonoCredito;
    waitForDeployment(): Promise<this>;

    interface: IRegistroProjetosCarbonoCreditoInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    marcarCreditosEmitidos: TypedContractMethod<
      [idProjeto: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    obterCreditosAprovados: TypedContractMethod<
      [idProjeto: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    obterProponente: TypedContractMethod<
      [idProjeto: BigNumberish, ],
      [string],
      'view'
    >
    

    
    projetoAprovado: TypedContractMethod<
      [idProjeto: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    projetoEmitido: TypedContractMethod<
      [idProjeto: BigNumberish, ],
      [boolean],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'marcarCreditosEmitidos'): TypedContractMethod<
      [idProjeto: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'obterCreditosAprovados'): TypedContractMethod<
      [idProjeto: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'obterProponente'): TypedContractMethod<
      [idProjeto: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'projetoAprovado'): TypedContractMethod<
      [idProjeto: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'projetoEmitido'): TypedContractMethod<
      [idProjeto: BigNumberish, ],
      [boolean],
      'view'
    >;

    

    filters: {
      
    };
  }