/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { ICertificadoCompensacaoNFTAposentadoria, ICertificadoCompensacaoNFTAposentadoriaInterface } from "../../RegistroAposentadorias.sol/ICertificadoCompensacaoNFTAposentadoria.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "beneficiario",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "idAposentadoria",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "quantidadeCompensada",
        "type": "uint256"
      },
      {
        "internalType": "string",
        "name": "descricao",
        "type": "string"
      },
      {
        "internalType": "string",
        "name": "uriCertificado",
        "type": "string"
      }
    ],
    "name": "emitirCertificado",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class ICertificadoCompensacaoNFTAposentadoria__factory {
    static readonly abi = _abi;
    static createInterface(): ICertificadoCompensacaoNFTAposentadoriaInterface {
      return new Interface(_abi) as ICertificadoCompensacaoNFTAposentadoriaInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): ICertificadoCompensacaoNFTAposentadoria {
      return new Contract(address, _abi, runner) as unknown as ICertificadoCompensacaoNFTAposentadoria;
    }
  }
  