/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { ICreditoCarbonoTokenAposentadoria, ICreditoCarbonoTokenAposentadoriaInterface } from "../../RegistroAposentadorias.sol/ICreditoCarbonoTokenAposentadoria.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "account",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "id",
        "type": "uint256"
      }
    ],
    "name": "balanceOf",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "titular",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "idLote",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "quantidade",
        "type": "uint256"
      }
    ],
    "name": "queimarCreditos",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class ICreditoCarbonoTokenAposentadoria__factory {
    static readonly abi = _abi;
    static createInterface(): ICreditoCarbonoTokenAposentadoriaInterface {
      return new Interface(_abi) as ICreditoCarbonoTokenAposentadoriaInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): ICreditoCarbonoTokenAposentadoria {
      return new Contract(address, _abi, runner) as unknown as ICreditoCarbonoTokenAposentadoria;
    }
  }
  