/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ICertificadoCompensacaoNFTAposentadoria__factory } from './ICertificadoCompensacaoNFTAposentadoria__factory.js';
export { ICreditoCarbonoTokenAposentadoria__factory } from './ICreditoCarbonoTokenAposentadoria__factory.js';
export { IRegistroOrganizacoesAposentadoria__factory } from './IRegistroOrganizacoesAposentadoria__factory.js';
export { ITesourariaCarbonoAposentadoria__factory } from './ITesourariaCarbonoAposentadoria__factory.js';
export { RegistroAposentadorias__factory } from './RegistroAposentadorias__factory.js';