/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { ITesourariaCarbonoAposentadoria, ITesourariaCarbonoAposentadoriaInterface } from "../../RegistroAposentadorias.sol/ITesourariaCarbonoAposentadoria.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "origem",
        "type": "string"
      }
    ],
    "name": "receberTaxaETH",
    "outputs": [],
    "stateMutability": "payable",
    "type": "function"
  }
] as const;

  export class ITesourariaCarbonoAposentadoria__factory {
    static readonly abi = _abi;
    static createInterface(): ITesourariaCarbonoAposentadoriaInterface {
      return new Interface(_abi) as ITesourariaCarbonoAposentadoriaInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): ITesourariaCarbonoAposentadoria {
      return new Contract(address, _abi, runner) as unknown as ITesourariaCarbonoAposentadoria;
    }
  }
  