/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IRegistroOrganizacoes } from './IRegistroOrganizacoes.js';
export type { ITesourariaCarbono } from './ITesourariaCarbono.js';
export type { RegistroProjetosCarbono } from './RegistroProjetosCarbono.js';