/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface RegistroProjetosCarbonoInterface extends Interface {
    getFunction(nameOrSignature: "alterarPrazoReenvioProjeto" | "alterarTaxaSubmissaoProjeto" | "autorizarContrato" | "cadastrarProjeto" | "contratosAutorizados" | "marcarCreditosEmitidos" | "marcarEmVotacao" | "obterCreditosAprovados" | "obterCreditosSolicitados" | "obterEstadoProjeto" | "obterProponente" | "owner" | "prazoReenvioProjeto" | "projetoAprovado" | "projetoEmitido" | "projetoJaCadastrado" | "projetos" | "reenviarProjeto" | "registrarResultadoValidacao" | "registroOrganizacoes" | "renounceOwnership" | "revogarProjeto" | "suspenderProjeto" | "taxaSubmissaoProjeto" | "tesourariaCarbono" | "totalProjetos" | "transferOwnership"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ContratoAutorizado" | "EstadoProjetoAlterado" | "OwnershipTransferred" | "PrazoReenvioProjetoAlterado" | "ProjetoCadastrado" | "ProjetoReenviado" | "ResultadoValidacaoRegistrado" | "TaxaSubmissaoProjetoAlterada"): EventFragment;

    encodeFunctionData(functionFragment: 'alterarPrazoReenvioProjeto', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'alterarTaxaSubmissaoProjeto', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'autorizarContrato', values: [AddressLike, boolean]): string;
encodeFunctionData(functionFragment: 'cadastrarProjeto', values: [string, string, string, BigNumberish, BigNumberish, string, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'contratosAutorizados', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'marcarCreditosEmitidos', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'marcarEmVotacao', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'obterCreditosAprovados', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'obterCreditosSolicitados', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'obterEstadoProjeto', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'obterProponente', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'prazoReenvioProjeto', values?: undefined): string;
encodeFunctionData(functionFragment: 'projetoAprovado', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'projetoEmitido', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'projetoJaCadastrado', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'projetos', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'reenviarProjeto', values: [BigNumberish, string, BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'registrarResultadoValidacao', values: [BigNumberish, boolean, BigNumberish]): string;
encodeFunctionData(functionFragment: 'registroOrganizacoes', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'revogarProjeto', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'suspenderProjeto', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'taxaSubmissaoProjeto', values?: undefined): string;
encodeFunctionData(functionFragment: 'tesourariaCarbono', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalProjetos', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'alterarPrazoReenvioProjeto', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'alterarTaxaSubmissaoProjeto', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'autorizarContrato', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cadastrarProjeto', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'contratosAutorizados', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'marcarCreditosEmitidos', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'marcarEmVotacao', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'obterCreditosAprovados', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'obterCreditosSolicitados', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'obterEstadoProjeto', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'obterProponente', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'prazoReenvioProjeto', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'projetoAprovado', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'projetoEmitido', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'projetoJaCadastrado', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'projetos', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'reenviarProjeto', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registrarResultadoValidacao', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registroOrganizacoes', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revogarProjeto', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'suspenderProjeto', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'taxaSubmissaoProjeto', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tesourariaCarbono', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalProjetos', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
  }

  
    export namespace ContratoAutorizadoEvent {
      export type InputTuple = [contrato: AddressLike, autorizado: boolean];
      export type OutputTuple = [contrato: string, autorizado: boolean];
      export interface OutputObject {contrato: string, autorizado: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EstadoProjetoAlteradoEvent {
      export type InputTuple = [idProjeto: BigNumberish, estadoProjeto: BigNumberish];
      export type OutputTuple = [idProjeto: bigint, estadoProjeto: bigint];
      export interface OutputObject {idProjeto: bigint, estadoProjeto: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PrazoReenvioProjetoAlteradoEvent {
      export type InputTuple = [novoPrazo: BigNumberish];
      export type OutputTuple = [novoPrazo: bigint];
      export interface OutputObject {novoPrazo: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProjetoCadastradoEvent {
      export type InputTuple = [idProjeto: BigNumberish, proponente: AddressLike, hashProjeto: BytesLike, creditosSolicitados: BigNumberish];
      export type OutputTuple = [idProjeto: bigint, proponente: string, hashProjeto: string, creditosSolicitados: bigint];
      export interface OutputObject {idProjeto: bigint, proponente: string, hashProjeto: string, creditosSolicitados: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProjetoReenviadoEvent {
      export type InputTuple = [idProjeto: BigNumberish, proponente: AddressLike, creditosSolicitados: BigNumberish];
      export type OutputTuple = [idProjeto: bigint, proponente: string, creditosSolicitados: bigint];
      export interface OutputObject {idProjeto: bigint, proponente: string, creditosSolicitados: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ResultadoValidacaoRegistradoEvent {
      export type InputTuple = [idProjeto: BigNumberish, aprovado: boolean, creditosAprovados: BigNumberish];
      export type OutputTuple = [idProjeto: bigint, aprovado: boolean, creditosAprovados: bigint];
      export interface OutputObject {idProjeto: bigint, aprovado: boolean, creditosAprovados: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TaxaSubmissaoProjetoAlteradaEvent {
      export type InputTuple = [novaTaxa: BigNumberish];
      export type OutputTuple = [novaTaxa: bigint];
      export interface OutputObject {novaTaxa: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface RegistroProjetosCarbono extends BaseContract {
    
    connect(runner?: ContractRunner | null): RegistroProjetosCarbono;
    waitForDeployment(): Promise<this>;

    interface: RegistroProjetosCarbonoInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    alterarPrazoReenvioProjeto: TypedContractMethod<
      [novoPrazo: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    alterarTaxaSubmissaoProjeto: TypedContractMethod<
      [novaTaxa: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    autorizarContrato: TypedContractMethod<
      [contrato: AddressLike, autorizado: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    cadastrarProjeto: TypedContractMethod<
      [nomeProjeto: string, descricao: string, localizacao: string, tipoProjeto: BigNumberish, creditosSolicitados: BigNumberish, uriEvidencias: string, inicioPeriodoReferencia: BigNumberish, fimPeriodoReferencia: BigNumberish, ],
      [bigint],
      'payable'
    >
    

    
    contratosAutorizados: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    marcarCreditosEmitidos: TypedContractMethod<
      [idProjeto: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    marcarEmVotacao: TypedContractMethod<
      [idProjeto: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    obterCreditosAprovados: TypedContractMethod<
      [idProjeto: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    obterCreditosSolicitados: TypedContractMethod<
      [idProjeto: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    obterEstadoProjeto: TypedContractMethod<
      [idProjeto: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    obterProponente: TypedContractMethod<
      [idProjeto: BigNumberish, ],
      [string],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    prazoReenvioProjeto: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    projetoAprovado: TypedContractMethod<
      [idProjeto: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    projetoEmitido: TypedContractMethod<
      [idProjeto: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    projetoJaCadastrado: TypedContractMethod<
      [arg0: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    projetos: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, string, string, bigint, bigint, bigint, string, string, bigint, bigint, bigint, bigint, bigint] & {idProjeto: bigint, proponente: string, nomeProjeto: string, descricao: string, localizacao: string, tipoProjeto: bigint, creditosSolicitados: bigint, creditosAprovados: bigint, uriEvidencias: string, hashProjeto: string, estadoProjeto: bigint, inicioPeriodoReferencia: bigint, fimPeriodoReferencia: bigint, dataSubmissao: bigint, dataUltimaRejeicao: bigint }],
      'view'
    >
    

    
    reenviarProjeto: TypedContractMethod<
      [idProjeto: BigNumberish, novaDescricao: string, novosCreditosSolicitados: BigNumberish, novaUriEvidencias: string, ],
      [void],
      'payable'
    >
    

    
    registrarResultadoValidacao: TypedContractMethod<
      [idProjeto: BigNumberish, aprovado: boolean, creditosAprovados: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    registroOrganizacoes: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    revogarProjeto: TypedContractMethod<
      [idProjeto: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    suspenderProjeto: TypedContractMethod<
      [idProjeto: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    taxaSubmissaoProjeto: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    tesourariaCarbono: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    totalProjetos: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'alterarPrazoReenvioProjeto'): TypedContractMethod<
      [novoPrazo: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'alterarTaxaSubmissaoProjeto'): TypedContractMethod<
      [novaTaxa: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'autorizarContrato'): TypedContractMethod<
      [contrato: AddressLike, autorizado: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'cadastrarProjeto'): TypedContractMethod<
      [nomeProjeto: string, descricao: string, localizacao: string, tipoProjeto: BigNumberish, creditosSolicitados: BigNumberish, uriEvidencias: string, inicioPeriodoReferencia: BigNumberish, fimPeriodoReferencia: BigNumberish, ],
      [bigint],
      'payable'
    >;
getFunction(nameOrSignature: 'contratosAutorizados'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'marcarCreditosEmitidos'): TypedContractMethod<
      [idProjeto: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'marcarEmVotacao'): TypedContractMethod<
      [idProjeto: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'obterCreditosAprovados'): TypedContractMethod<
      [idProjeto: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'obterCreditosSolicitados'): TypedContractMethod<
      [idProjeto: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'obterEstadoProjeto'): TypedContractMethod<
      [idProjeto: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'obterProponente'): TypedContractMethod<
      [idProjeto: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'prazoReenvioProjeto'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'projetoAprovado'): TypedContractMethod<
      [idProjeto: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'projetoEmitido'): TypedContractMethod<
      [idProjeto: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'projetoJaCadastrado'): TypedContractMethod<
      [arg0: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'projetos'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, string, string, bigint, bigint, bigint, string, string, bigint, bigint, bigint, bigint, bigint] & {idProjeto: bigint, proponente: string, nomeProjeto: string, descricao: string, localizacao: string, tipoProjeto: bigint, creditosSolicitados: bigint, creditosAprovados: bigint, uriEvidencias: string, hashProjeto: string, estadoProjeto: bigint, inicioPeriodoReferencia: bigint, fimPeriodoReferencia: bigint, dataSubmissao: bigint, dataUltimaRejeicao: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'reenviarProjeto'): TypedContractMethod<
      [idProjeto: BigNumberish, novaDescricao: string, novosCreditosSolicitados: BigNumberish, novaUriEvidencias: string, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'registrarResultadoValidacao'): TypedContractMethod<
      [idProjeto: BigNumberish, aprovado: boolean, creditosAprovados: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'registroOrganizacoes'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revogarProjeto'): TypedContractMethod<
      [idProjeto: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'suspenderProjeto'): TypedContractMethod<
      [idProjeto: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'taxaSubmissaoProjeto'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'tesourariaCarbono'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'totalProjetos'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'ContratoAutorizado'): TypedContractEvent<ContratoAutorizadoEvent.InputTuple, ContratoAutorizadoEvent.OutputTuple, ContratoAutorizadoEvent.OutputObject>;
getEvent(key: 'EstadoProjetoAlterado'): TypedContractEvent<EstadoProjetoAlteradoEvent.InputTuple, EstadoProjetoAlteradoEvent.OutputTuple, EstadoProjetoAlteradoEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'PrazoReenvioProjetoAlterado'): TypedContractEvent<PrazoReenvioProjetoAlteradoEvent.InputTuple, PrazoReenvioProjetoAlteradoEvent.OutputTuple, PrazoReenvioProjetoAlteradoEvent.OutputObject>;
getEvent(key: 'ProjetoCadastrado'): TypedContractEvent<ProjetoCadastradoEvent.InputTuple, ProjetoCadastradoEvent.OutputTuple, ProjetoCadastradoEvent.OutputObject>;
getEvent(key: 'ProjetoReenviado'): TypedContractEvent<ProjetoReenviadoEvent.InputTuple, ProjetoReenviadoEvent.OutputTuple, ProjetoReenviadoEvent.OutputObject>;
getEvent(key: 'ResultadoValidacaoRegistrado'): TypedContractEvent<ResultadoValidacaoRegistradoEvent.InputTuple, ResultadoValidacaoRegistradoEvent.OutputTuple, ResultadoValidacaoRegistradoEvent.OutputObject>;
getEvent(key: 'TaxaSubmissaoProjetoAlterada'): TypedContractEvent<TaxaSubmissaoProjetoAlteradaEvent.InputTuple, TaxaSubmissaoProjetoAlteradaEvent.OutputTuple, TaxaSubmissaoProjetoAlteradaEvent.OutputObject>;

    filters: {
      
      'ContratoAutorizado(address,bool)': TypedContractEvent<ContratoAutorizadoEvent.InputTuple, ContratoAutorizadoEvent.OutputTuple, ContratoAutorizadoEvent.OutputObject>;
      ContratoAutorizado: TypedContractEvent<ContratoAutorizadoEvent.InputTuple, ContratoAutorizadoEvent.OutputTuple, ContratoAutorizadoEvent.OutputObject>;
    

      'EstadoProjetoAlterado(uint256,uint8)': TypedContractEvent<EstadoProjetoAlteradoEvent.InputTuple, EstadoProjetoAlteradoEvent.OutputTuple, EstadoProjetoAlteradoEvent.OutputObject>;
      EstadoProjetoAlterado: TypedContractEvent<EstadoProjetoAlteradoEvent.InputTuple, EstadoProjetoAlteradoEvent.OutputTuple, EstadoProjetoAlteradoEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'PrazoReenvioProjetoAlterado(uint256)': TypedContractEvent<PrazoReenvioProjetoAlteradoEvent.InputTuple, PrazoReenvioProjetoAlteradoEvent.OutputTuple, PrazoReenvioProjetoAlteradoEvent.OutputObject>;
      PrazoReenvioProjetoAlterado: TypedContractEvent<PrazoReenvioProjetoAlteradoEvent.InputTuple, PrazoReenvioProjetoAlteradoEvent.OutputTuple, PrazoReenvioProjetoAlteradoEvent.OutputObject>;
    

      'ProjetoCadastrado(uint256,address,bytes32,uint256)': TypedContractEvent<ProjetoCadastradoEvent.InputTuple, ProjetoCadastradoEvent.OutputTuple, ProjetoCadastradoEvent.OutputObject>;
      ProjetoCadastrado: TypedContractEvent<ProjetoCadastradoEvent.InputTuple, ProjetoCadastradoEvent.OutputTuple, ProjetoCadastradoEvent.OutputObject>;
    

      'ProjetoReenviado(uint256,address,uint256)': TypedContractEvent<ProjetoReenviadoEvent.InputTuple, ProjetoReenviadoEvent.OutputTuple, ProjetoReenviadoEvent.OutputObject>;
      ProjetoReenviado: TypedContractEvent<ProjetoReenviadoEvent.InputTuple, ProjetoReenviadoEvent.OutputTuple, ProjetoReenviadoEvent.OutputObject>;
    

      'ResultadoValidacaoRegistrado(uint256,bool,uint256)': TypedContractEvent<ResultadoValidacaoRegistradoEvent.InputTuple, ResultadoValidacaoRegistradoEvent.OutputTuple, ResultadoValidacaoRegistradoEvent.OutputObject>;
      ResultadoValidacaoRegistrado: TypedContractEvent<ResultadoValidacaoRegistradoEvent.InputTuple, ResultadoValidacaoRegistradoEvent.OutputTuple, ResultadoValidacaoRegistradoEvent.OutputObject>;
    

      'TaxaSubmissaoProjetoAlterada(uint256)': TypedContractEvent<TaxaSubmissaoProjetoAlteradaEvent.InputTuple, TaxaSubmissaoProjetoAlteradaEvent.OutputTuple, TaxaSubmissaoProjetoAlteradaEvent.OutputObject>;
      TaxaSubmissaoProjetoAlterada: TypedContractEvent<TaxaSubmissaoProjetoAlteradaEvent.InputTuple, TaxaSubmissaoProjetoAlteradaEvent.OutputTuple, TaxaSubmissaoProjetoAlteradaEvent.OutputObject>;
    
    };
  }