/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IRegistroOrganizacoesValidacao } from './IRegistroOrganizacoesValidacao.js';
export type { IRegistroProjetosCarbonoValidacao } from './IRegistroProjetosCarbonoValidacao.js';
export type { IStakingCarbonoValidacao } from './IStakingCarbonoValidacao.js';
export type { ValidacaoProjetos } from './ValidacaoProjetos.js';