/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface IRegistroProjetosCarbonoValidacaoInterface extends Interface {
    getFunction(nameOrSignature: "marcarEmVotacao" | "obterCreditosSolicitados" | "registrarResultadoValidacao"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'marcarEmVotacao', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'obterCreditosSolicitados', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'registrarResultadoValidacao', values: [BigNumberish, boolean, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'marcarEmVotacao', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'obterCreditosSolicitados', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registrarResultadoValidacao', data: BytesLike): Result;
  }

  

  export interface IRegistroProjetosCarbonoValidacao extends BaseContract {
    
    connect(runner?: ContractRunner | null): IRegistroProjetosCarbonoValidacao;
    waitForDeployment(): Promise<this>;

    interface: IRegistroProjetosCarbonoValidacaoInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    marcarEmVotacao: TypedContractMethod<
      [idProjeto: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    obterCreditosSolicitados: TypedContractMethod<
      [idProjeto: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    registrarResultadoValidacao: TypedContractMethod<
      [idProjeto: BigNumberish, aprovado: boolean, creditosAprovados: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'marcarEmVotacao'): TypedContractMethod<
      [idProjeto: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'obterCreditosSolicitados'): TypedContractMethod<
      [idProjeto: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'registrarResultadoValidacao'): TypedContractMethod<
      [idProjeto: BigNumberish, aprovado: boolean, creditosAprovados: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }