/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface ValidacaoProjetosInterface extends Interface {
    getFunction(nameOrSignature: "alterarParametrosVotacao" | "configurarStakeValidador" | "encerrarVotacao" | "exigirStakeMinimo" | "iniciarVotacao" | "jaVotou" | "owner" | "prazoVotacao" | "quorumMinimo" | "registroOrganizacoes" | "registroProjetosCarbono" | "renounceOwnership" | "stakeMinimoValidador" | "stakingCarbono" | "totalVotos" | "transferOwnership" | "validadorApto" | "votacaoAberta" | "votacoes" | "votarProjeto" | "votos"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ConfiguracaoStakeAlterada" | "OwnershipTransferred" | "ParametrosVotacaoAlterados" | "VotacaoEncerrada" | "VotacaoIniciada" | "VotoRegistrado"): EventFragment;

    encodeFunctionData(functionFragment: 'alterarParametrosVotacao', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'configurarStakeValidador', values: [AddressLike, boolean, BigNumberish]): string;
encodeFunctionData(functionFragment: 'encerrarVotacao', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'exigirStakeMinimo', values?: undefined): string;
encodeFunctionData(functionFragment: 'iniciarVotacao', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'jaVotou', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'prazoVotacao', values?: undefined): string;
encodeFunctionData(functionFragment: 'quorumMinimo', values?: undefined): string;
encodeFunctionData(functionFragment: 'registroOrganizacoes', values?: undefined): string;
encodeFunctionData(functionFragment: 'registroProjetosCarbono', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'stakeMinimoValidador', values?: undefined): string;
encodeFunctionData(functionFragment: 'stakingCarbono', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalVotos', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'validadorApto', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'votacaoAberta', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'votacoes', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'votarProjeto', values: [BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'votos', values: [BigNumberish, AddressLike]): string;

    decodeFunctionResult(functionFragment: 'alterarParametrosVotacao', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'configurarStakeValidador', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'encerrarVotacao', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'exigirStakeMinimo', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'iniciarVotacao', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'jaVotou', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'prazoVotacao', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'quorumMinimo', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registroOrganizacoes', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registroProjetosCarbono', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'stakeMinimoValidador', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'stakingCarbono', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalVotos', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'validadorApto', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'votacaoAberta', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'votacoes', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'votarProjeto', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'votos', data: BytesLike): Result;
  }

  
    export namespace ConfiguracaoStakeAlteradaEvent {
      export type InputTuple = [enderecoStaking: AddressLike, exigirStakeMinimo: boolean, stakeMinimoValidador: BigNumberish];
      export type OutputTuple = [enderecoStaking: string, exigirStakeMinimo: boolean, stakeMinimoValidador: bigint];
      export interface OutputObject {enderecoStaking: string, exigirStakeMinimo: boolean, stakeMinimoValidador: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ParametrosVotacaoAlteradosEvent {
      export type InputTuple = [prazoVotacao: BigNumberish, quorumMinimo: BigNumberish];
      export type OutputTuple = [prazoVotacao: bigint, quorumMinimo: bigint];
      export interface OutputObject {prazoVotacao: bigint, quorumMinimo: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace VotacaoEncerradaEvent {
      export type InputTuple = [idProjeto: BigNumberish, aprovado: boolean, creditosAprovados: BigNumberish, votosAprovacao: BigNumberish, votosRejeicao: BigNumberish];
      export type OutputTuple = [idProjeto: bigint, aprovado: boolean, creditosAprovados: bigint, votosAprovacao: bigint, votosRejeicao: bigint];
      export interface OutputObject {idProjeto: bigint, aprovado: boolean, creditosAprovados: bigint, votosAprovacao: bigint, votosRejeicao: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace VotacaoIniciadaEvent {
      export type InputTuple = [idProjeto: BigNumberish, iniciador: AddressLike, inicioVotacao: BigNumberish, fimVotacao: BigNumberish];
      export type OutputTuple = [idProjeto: bigint, iniciador: string, inicioVotacao: bigint, fimVotacao: bigint];
      export interface OutputObject {idProjeto: bigint, iniciador: string, inicioVotacao: bigint, fimVotacao: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace VotoRegistradoEvent {
      export type InputTuple = [idProjeto: BigNumberish, validador: AddressLike, voto: BigNumberish, creditosSugeridos: BigNumberish];
      export type OutputTuple = [idProjeto: bigint, validador: string, voto: bigint, creditosSugeridos: bigint];
      export interface OutputObject {idProjeto: bigint, validador: string, voto: bigint, creditosSugeridos: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface ValidacaoProjetos extends BaseContract {
    
    connect(runner?: ContractRunner | null): ValidacaoProjetos;
    waitForDeployment(): Promise<this>;

    interface: ValidacaoProjetosInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    alterarParametrosVotacao: TypedContractMethod<
      [novoPrazoVotacao: BigNumberish, novoQuorumMinimo: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    configurarStakeValidador: TypedContractMethod<
      [enderecoStaking: AddressLike, exigirStake: boolean, novoStakeMinimo: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    encerrarVotacao: TypedContractMethod<
      [idProjeto: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    exigirStakeMinimo: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    iniciarVotacao: TypedContractMethod<
      [idProjeto: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    jaVotou: TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    prazoVotacao: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    quorumMinimo: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    registroOrganizacoes: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    registroProjetosCarbono: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    stakeMinimoValidador: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    stakingCarbono: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    totalVotos: TypedContractMethod<
      [idProjeto: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    validadorApto: TypedContractMethod<
      [carteira: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    votacaoAberta: TypedContractMethod<
      [idProjeto: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    votacoes: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, bigint, bigint, bigint, bigint, bigint, bigint, boolean, boolean, bigint] & {idProjeto: bigint, inicioVotacao: bigint, fimVotacao: bigint, votosAprovacao: bigint, votosRejeicao: bigint, somaCreditosSugeridos: bigint, quantidadeSugestoes: bigint, encerrada: boolean, aprovado: boolean, creditosAprovados: bigint }],
      'view'
    >
    

    
    votarProjeto: TypedContractMethod<
      [idProjeto: BigNumberish, voto: BigNumberish, creditosSugeridos: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    votos: TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'alterarParametrosVotacao'): TypedContractMethod<
      [novoPrazoVotacao: BigNumberish, novoQuorumMinimo: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'configurarStakeValidador'): TypedContractMethod<
      [enderecoStaking: AddressLike, exigirStake: boolean, novoStakeMinimo: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'encerrarVotacao'): TypedContractMethod<
      [idProjeto: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'exigirStakeMinimo'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'iniciarVotacao'): TypedContractMethod<
      [idProjeto: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'jaVotou'): TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'prazoVotacao'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'quorumMinimo'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'registroOrganizacoes'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'registroProjetosCarbono'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'stakeMinimoValidador'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'stakingCarbono'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'totalVotos'): TypedContractMethod<
      [idProjeto: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'validadorApto'): TypedContractMethod<
      [carteira: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'votacaoAberta'): TypedContractMethod<
      [idProjeto: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'votacoes'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, bigint, bigint, bigint, bigint, bigint, bigint, boolean, boolean, bigint] & {idProjeto: bigint, inicioVotacao: bigint, fimVotacao: bigint, votosAprovacao: bigint, votosRejeicao: bigint, somaCreditosSugeridos: bigint, quantidadeSugestoes: bigint, encerrada: boolean, aprovado: boolean, creditosAprovados: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'votarProjeto'): TypedContractMethod<
      [idProjeto: BigNumberish, voto: BigNumberish, creditosSugeridos: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'votos'): TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [bigint],
      'view'
    >;

    getEvent(key: 'ConfiguracaoStakeAlterada'): TypedContractEvent<ConfiguracaoStakeAlteradaEvent.InputTuple, ConfiguracaoStakeAlteradaEvent.OutputTuple, ConfiguracaoStakeAlteradaEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'ParametrosVotacaoAlterados'): TypedContractEvent<ParametrosVotacaoAlteradosEvent.InputTuple, ParametrosVotacaoAlteradosEvent.OutputTuple, ParametrosVotacaoAlteradosEvent.OutputObject>;
getEvent(key: 'VotacaoEncerrada'): TypedContractEvent<VotacaoEncerradaEvent.InputTuple, VotacaoEncerradaEvent.OutputTuple, VotacaoEncerradaEvent.OutputObject>;
getEvent(key: 'VotacaoIniciada'): TypedContractEvent<VotacaoIniciadaEvent.InputTuple, VotacaoIniciadaEvent.OutputTuple, VotacaoIniciadaEvent.OutputObject>;
getEvent(key: 'VotoRegistrado'): TypedContractEvent<VotoRegistradoEvent.InputTuple, VotoRegistradoEvent.OutputTuple, VotoRegistradoEvent.OutputObject>;

    filters: {
      
      'ConfiguracaoStakeAlterada(address,bool,uint256)': TypedContractEvent<ConfiguracaoStakeAlteradaEvent.InputTuple, ConfiguracaoStakeAlteradaEvent.OutputTuple, ConfiguracaoStakeAlteradaEvent.OutputObject>;
      ConfiguracaoStakeAlterada: TypedContractEvent<ConfiguracaoStakeAlteradaEvent.InputTuple, ConfiguracaoStakeAlteradaEvent.OutputTuple, ConfiguracaoStakeAlteradaEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'ParametrosVotacaoAlterados(uint256,uint256)': TypedContractEvent<ParametrosVotacaoAlteradosEvent.InputTuple, ParametrosVotacaoAlteradosEvent.OutputTuple, ParametrosVotacaoAlteradosEvent.OutputObject>;
      ParametrosVotacaoAlterados: TypedContractEvent<ParametrosVotacaoAlteradosEvent.InputTuple, ParametrosVotacaoAlteradosEvent.OutputTuple, ParametrosVotacaoAlteradosEvent.OutputObject>;
    

      'VotacaoEncerrada(uint256,bool,uint256,uint256,uint256)': TypedContractEvent<VotacaoEncerradaEvent.InputTuple, VotacaoEncerradaEvent.OutputTuple, VotacaoEncerradaEvent.OutputObject>;
      VotacaoEncerrada: TypedContractEvent<VotacaoEncerradaEvent.InputTuple, VotacaoEncerradaEvent.OutputTuple, VotacaoEncerradaEvent.OutputObject>;
    

      'VotacaoIniciada(uint256,address,uint256,uint256)': TypedContractEvent<VotacaoIniciadaEvent.InputTuple, VotacaoIniciadaEvent.OutputTuple, VotacaoIniciadaEvent.OutputObject>;
      VotacaoIniciada: TypedContractEvent<VotacaoIniciadaEvent.InputTuple, VotacaoIniciadaEvent.OutputTuple, VotacaoIniciadaEvent.OutputObject>;
    

      'VotoRegistrado(uint256,address,uint8,uint256)': TypedContractEvent<VotoRegistradoEvent.InputTuple, VotoRegistradoEvent.OutputTuple, VotoRegistradoEvent.OutputObject>;
      VotoRegistrado: TypedContractEvent<VotoRegistradoEvent.InputTuple, VotoRegistradoEvent.OutputTuple, VotoRegistradoEvent.OutputObject>;
    
    };
  }