/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AdaptadorOraculoChainlink } from './AdaptadorOraculoChainlink.js';
export type { AggregatorV3Interface } from './AggregatorV3Interface.js';