/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface StakingCarbonoInterface extends Interface {
    getFunction(nameOrSignature: "BASE_BPS" | "alterarParametrosStaking" | "atualizarContratos" | "calcularRecompensaPendente" | "dataInicioStake" | "dataUltimoCalculo" | "depositarStake" | "owner" | "periodoMinimoBloqueio" | "possuiStakeMinimoValidador" | "recompensasAcumuladas" | "renounceOwnership" | "resgatarRecompensa" | "sacarStake" | "saldoEmStake" | "stakeMinimoValidador" | "taxaRecompensaAnualBps" | "tesourariaCarbono" | "tokenImpactoCarbono" | "totalEmStake" | "transferOwnership"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ContratosAtualizados" | "OwnershipTransferred" | "ParametrosStakingAlterados" | "RecompensaResgatada" | "StakeDepositado" | "StakeSacado"): EventFragment;

    encodeFunctionData(functionFragment: 'BASE_BPS', values?: undefined): string;
encodeFunctionData(functionFragment: 'alterarParametrosStaking', values: [BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'atualizarContratos', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'calcularRecompensaPendente', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'dataInicioStake', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'dataUltimoCalculo', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'depositarStake', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'periodoMinimoBloqueio', values?: undefined): string;
encodeFunctionData(functionFragment: 'possuiStakeMinimoValidador', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'recompensasAcumuladas', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'resgatarRecompensa', values?: undefined): string;
encodeFunctionData(functionFragment: 'sacarStake', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'saldoEmStake', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'stakeMinimoValidador', values?: undefined): string;
encodeFunctionData(functionFragment: 'taxaRecompensaAnualBps', values?: undefined): string;
encodeFunctionData(functionFragment: 'tesourariaCarbono', values?: undefined): string;
encodeFunctionData(functionFragment: 'tokenImpactoCarbono', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalEmStake', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'BASE_BPS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'alterarParametrosStaking', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'atualizarContratos', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'calcularRecompensaPendente', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'dataInicioStake', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'dataUltimoCalculo', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'depositarStake', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'periodoMinimoBloqueio', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'possuiStakeMinimoValidador', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'recompensasAcumuladas', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'resgatarRecompensa', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'sacarStake', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'saldoEmStake', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'stakeMinimoValidador', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'taxaRecompensaAnualBps', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tesourariaCarbono', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tokenImpactoCarbono', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalEmStake', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
  }

  
    export namespace ContratosAtualizadosEvent {
      export type InputTuple = [tokenImpactoCarbono: AddressLike, tesourariaCarbono: AddressLike];
      export type OutputTuple = [tokenImpactoCarbono: string, tesourariaCarbono: string];
      export interface OutputObject {tokenImpactoCarbono: string, tesourariaCarbono: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ParametrosStakingAlteradosEvent {
      export type InputTuple = [stakeMinimoValidador: BigNumberish, periodoMinimoBloqueio: BigNumberish, taxaRecompensaAnualBps: BigNumberish];
      export type OutputTuple = [stakeMinimoValidador: bigint, periodoMinimoBloqueio: bigint, taxaRecompensaAnualBps: bigint];
      export interface OutputObject {stakeMinimoValidador: bigint, periodoMinimoBloqueio: bigint, taxaRecompensaAnualBps: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RecompensaResgatadaEvent {
      export type InputTuple = [participante: AddressLike, quantidade: BigNumberish];
      export type OutputTuple = [participante: string, quantidade: bigint];
      export interface OutputObject {participante: string, quantidade: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace StakeDepositadoEvent {
      export type InputTuple = [participante: AddressLike, quantidade: BigNumberish, novoSaldo: BigNumberish];
      export type OutputTuple = [participante: string, quantidade: bigint, novoSaldo: bigint];
      export interface OutputObject {participante: string, quantidade: bigint, novoSaldo: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace StakeSacadoEvent {
      export type InputTuple = [participante: AddressLike, quantidade: BigNumberish, saldoRestante: BigNumberish];
      export type OutputTuple = [participante: string, quantidade: bigint, saldoRestante: bigint];
      export interface OutputObject {participante: string, quantidade: bigint, saldoRestante: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface StakingCarbono extends BaseContract {
    
    connect(runner?: ContractRunner | null): StakingCarbono;
    waitForDeployment(): Promise<this>;

    interface: StakingCarbonoInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    BASE_BPS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    alterarParametrosStaking: TypedContractMethod<
      [novoStakeMinimoValidador: BigNumberish, novoPeriodoMinimoBloqueio: BigNumberish, novaTaxaRecompensaAnualBps: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    atualizarContratos: TypedContractMethod<
      [enderecoTokenImpactoCarbono: AddressLike, enderecoTesourariaCarbono: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    calcularRecompensaPendente: TypedContractMethod<
      [participante: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    dataInicioStake: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    dataUltimoCalculo: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    depositarStake: TypedContractMethod<
      [quantidade: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    periodoMinimoBloqueio: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    possuiStakeMinimoValidador: TypedContractMethod<
      [participante: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    recompensasAcumuladas: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    resgatarRecompensa: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    sacarStake: TypedContractMethod<
      [quantidade: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    saldoEmStake: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    stakeMinimoValidador: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    taxaRecompensaAnualBps: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    tesourariaCarbono: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    tokenImpactoCarbono: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    totalEmStake: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'BASE_BPS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'alterarParametrosStaking'): TypedContractMethod<
      [novoStakeMinimoValidador: BigNumberish, novoPeriodoMinimoBloqueio: BigNumberish, novaTaxaRecompensaAnualBps: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'atualizarContratos'): TypedContractMethod<
      [enderecoTokenImpactoCarbono: AddressLike, enderecoTesourariaCarbono: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'calcularRecompensaPendente'): TypedContractMethod<
      [participante: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'dataInicioStake'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'dataUltimoCalculo'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'depositarStake'): TypedContractMethod<
      [quantidade: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'periodoMinimoBloqueio'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'possuiStakeMinimoValidador'): TypedContractMethod<
      [participante: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'recompensasAcumuladas'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'resgatarRecompensa'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'sacarStake'): TypedContractMethod<
      [quantidade: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'saldoEmStake'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'stakeMinimoValidador'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'taxaRecompensaAnualBps'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'tesourariaCarbono'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'tokenImpactoCarbono'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'totalEmStake'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'ContratosAtualizados'): TypedContractEvent<ContratosAtualizadosEvent.InputTuple, ContratosAtualizadosEvent.OutputTuple, ContratosAtualizadosEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'ParametrosStakingAlterados'): TypedContractEvent<ParametrosStakingAlteradosEvent.InputTuple, ParametrosStakingAlteradosEvent.OutputTuple, ParametrosStakingAlteradosEvent.OutputObject>;
getEvent(key: 'RecompensaResgatada'): TypedContractEvent<RecompensaResgatadaEvent.InputTuple, RecompensaResgatadaEvent.OutputTuple, RecompensaResgatadaEvent.OutputObject>;
getEvent(key: 'StakeDepositado'): TypedContractEvent<StakeDepositadoEvent.InputTuple, StakeDepositadoEvent.OutputTuple, StakeDepositadoEvent.OutputObject>;
getEvent(key: 'StakeSacado'): TypedContractEvent<StakeSacadoEvent.InputTuple, StakeSacadoEvent.OutputTuple, StakeSacadoEvent.OutputObject>;

    filters: {
      
      'ContratosAtualizados(address,address)': TypedContractEvent<ContratosAtualizadosEvent.InputTuple, ContratosAtualizadosEvent.OutputTuple, ContratosAtualizadosEvent.OutputObject>;
      ContratosAtualizados: TypedContractEvent<ContratosAtualizadosEvent.InputTuple, ContratosAtualizadosEvent.OutputTuple, ContratosAtualizadosEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'ParametrosStakingAlterados(uint256,uint256,uint256)': TypedContractEvent<ParametrosStakingAlteradosEvent.InputTuple, ParametrosStakingAlteradosEvent.OutputTuple, ParametrosStakingAlteradosEvent.OutputObject>;
      ParametrosStakingAlterados: TypedContractEvent<ParametrosStakingAlteradosEvent.InputTuple, ParametrosStakingAlteradosEvent.OutputTuple, ParametrosStakingAlteradosEvent.OutputObject>;
    

      'RecompensaResgatada(address,uint256)': TypedContractEvent<RecompensaResgatadaEvent.InputTuple, RecompensaResgatadaEvent.OutputTuple, RecompensaResgatadaEvent.OutputObject>;
      RecompensaResgatada: TypedContractEvent<RecompensaResgatadaEvent.InputTuple, RecompensaResgatadaEvent.OutputTuple, RecompensaResgatadaEvent.OutputObject>;
    

      'StakeDepositado(address,uint256,uint256)': TypedContractEvent<StakeDepositadoEvent.InputTuple, StakeDepositadoEvent.OutputTuple, StakeDepositadoEvent.OutputObject>;
      StakeDepositado: TypedContractEvent<StakeDepositadoEvent.InputTuple, StakeDepositadoEvent.OutputTuple, StakeDepositadoEvent.OutputObject>;
    

      'StakeSacado(address,uint256,uint256)': TypedContractEvent<StakeSacadoEvent.InputTuple, StakeSacadoEvent.OutputTuple, StakeSacadoEvent.OutputObject>;
      StakeSacado: TypedContractEvent<StakeSacadoEvent.InputTuple, StakeSacadoEvent.OutputTuple, StakeSacadoEvent.OutputObject>;
    
    };
  }