/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ITesourariaCarbonoStaking__factory } from './ITesourariaCarbonoStaking__factory.js';
export { StakingCarbono__factory } from './StakingCarbono__factory.js';