/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { ITesourariaCarbonoStaking, ITesourariaCarbonoStakingInterface } from "../../StakingCarbono.sol/ITesourariaCarbonoStaking.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "destinatario",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "quantidade",
        "type": "uint256"
      },
      {
        "internalType": "string",
        "name": "finalidade",
        "type": "string"
      }
    ],
    "name": "enviarTICAutorizado",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class ITesourariaCarbonoStaking__factory {
    static readonly abi = _abi;
    static createInterface(): ITesourariaCarbonoStakingInterface {
      return new Interface(_abi) as ITesourariaCarbonoStakingInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): ITesourariaCarbonoStaking {
      return new Contract(address, _abi, runner) as unknown as ITesourariaCarbonoStaking;
    }
  }
  