/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IRegistroOrganizacoes__factory } from './IRegistroOrganizacoes__factory.js';
export { ITesourariaCarbono__factory } from './ITesourariaCarbono__factory.js';
export { RegistroProjetosCarbono__factory } from './RegistroProjetosCarbono__factory.js';