/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IRegistroOrganizacoes, IRegistroOrganizacoesInterface } from "../../RegistroProjetosCarbono.sol/IRegistroOrganizacoes.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "carteira",
        "type": "address"
      }
    ],
    "name": "ehProponente",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class IRegistroOrganizacoes__factory {
    static readonly abi = _abi;
    static createInterface(): IRegistroOrganizacoesInterface {
      return new Interface(_abi) as IRegistroOrganizacoesInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IRegistroOrganizacoes {
      return new Contract(address, _abi, runner) as unknown as IRegistroOrganizacoes;
    }
  }
  