/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { ITesourariaCarbono, ITesourariaCarbonoInterface } from "../../RegistroProjetosCarbono.sol/ITesourariaCarbono.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "origem",
        "type": "string"
      }
    ],
    "name": "receberTaxaETH",
    "outputs": [],
    "stateMutability": "payable",
    "type": "function"
  }
] as const;

  export class ITesourariaCarbono__factory {
    static readonly abi = _abi;
    static createInterface(): ITesourariaCarbonoInterface {
      return new Interface(_abi) as ITesourariaCarbonoInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): ITesourariaCarbono {
      return new Contract(address, _abi, runner) as unknown as ITesourariaCarbono;
    }
  }
  