/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IRegistroOrganizacoesMercado, IRegistroOrganizacoesMercadoInterface } from "../../MercadoCarbono.sol/IRegistroOrganizacoesMercado.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "carteira",
        "type": "address"
      }
    ],
    "name": "ehComprador",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "carteira",
        "type": "address"
      }
    ],
    "name": "organizacaoAtiva",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class IRegistroOrganizacoesMercado__factory {
    static readonly abi = _abi;
    static createInterface(): IRegistroOrganizacoesMercadoInterface {
      return new Interface(_abi) as IRegistroOrganizacoesMercadoInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IRegistroOrganizacoesMercado {
      return new Contract(address, _abi, runner) as unknown as IRegistroOrganizacoesMercado;
    }
  }
  