/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { ITesourariaCarbonoMercado, ITesourariaCarbonoMercadoInterface } from "../../MercadoCarbono.sol/ITesourariaCarbonoMercado.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "origem",
        "type": "string"
      }
    ],
    "name": "receberTaxaETH",
    "outputs": [],
    "stateMutability": "payable",
    "type": "function"
  }
] as const;

  export class ITesourariaCarbonoMercado__factory {
    static readonly abi = _abi;
    static createInterface(): ITesourariaCarbonoMercadoInterface {
      return new Interface(_abi) as ITesourariaCarbonoMercadoInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): ITesourariaCarbonoMercado {
      return new Contract(address, _abi, runner) as unknown as ITesourariaCarbonoMercado;
    }
  }
  