/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface ICertificadoCompensacaoNFTAposentadoriaInterface extends Interface {
    getFunction(nameOrSignature: "emitirCertificado"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'emitirCertificado', values: [AddressLike, BigNumberish, BigNumberish, string, string]): string;

    decodeFunctionResult(functionFragment: 'emitirCertificado', data: BytesLike): Result;
  }

  

  export interface ICertificadoCompensacaoNFTAposentadoria extends BaseContract {
    
    connect(runner?: ContractRunner | null): ICertificadoCompensacaoNFTAposentadoria;
    waitForDeployment(): Promise<this>;

    interface: ICertificadoCompensacaoNFTAposentadoriaInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    emitirCertificado: TypedContractMethod<
      [beneficiario: AddressLike, idAposentadoria: BigNumberish, quantidadeCompensada: BigNumberish, descricao: string, uriCertificado: string, ],
      [bigint],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'emitirCertificado'): TypedContractMethod<
      [beneficiario: AddressLike, idAposentadoria: BigNumberish, quantidadeCompensada: BigNumberish, descricao: string, uriCertificado: string, ],
      [bigint],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }