/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ICertificadoCompensacaoNFTAposentadoria } from './ICertificadoCompensacaoNFTAposentadoria.js';
export type { ICreditoCarbonoTokenAposentadoria } from './ICreditoCarbonoTokenAposentadoria.js';
export type { IRegistroOrganizacoesAposentadoria } from './IRegistroOrganizacoesAposentadoria.js';
export type { ITesourariaCarbonoAposentadoria } from './ITesourariaCarbonoAposentadoria.js';
export type { RegistroAposentadorias } from './RegistroAposentadorias.js';