/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface RegistroAposentadoriasInterface extends Interface {
    getFunction(nameOrSignature: "alterarTaxaAposentadoria" | "aposentadoriaExiste" | "aposentadorias" | "aposentarCreditos" | "atualizarContratos" | "certificadoCompensacaoNFT" | "creditoCarbonoToken" | "owner" | "registroOrganizacoes" | "renounceOwnership" | "taxaAposentadoria" | "tesourariaCarbono" | "totalAposentadoPorLote" | "totalAposentadorias" | "totalCompensadoPorComprador" | "transferOwnership"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ContratosAtualizados" | "CreditosAposentados" | "OwnershipTransferred" | "TaxaAposentadoriaAlterada"): EventFragment;

    encodeFunctionData(functionFragment: 'alterarTaxaAposentadoria', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'aposentadoriaExiste', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'aposentadorias', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'aposentarCreditos', values: [BigNumberish, BigNumberish, string, string, string]): string;
encodeFunctionData(functionFragment: 'atualizarContratos', values: [AddressLike, AddressLike, AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'certificadoCompensacaoNFT', values?: undefined): string;
encodeFunctionData(functionFragment: 'creditoCarbonoToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'registroOrganizacoes', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'taxaAposentadoria', values?: undefined): string;
encodeFunctionData(functionFragment: 'tesourariaCarbono', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalAposentadoPorLote', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'totalAposentadorias', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalCompensadoPorComprador', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'alterarTaxaAposentadoria', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'aposentadoriaExiste', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'aposentadorias', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'aposentarCreditos', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'atualizarContratos', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'certificadoCompensacaoNFT', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'creditoCarbonoToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registroOrganizacoes', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'taxaAposentadoria', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tesourariaCarbono', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalAposentadoPorLote', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalAposentadorias', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalCompensadoPorComprador', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
  }

  
    export namespace ContratosAtualizadosEvent {
      export type InputTuple = [registroOrganizacoes: AddressLike, creditoCarbonoToken: AddressLike, certificadoCompensacaoNFT: AddressLike, tesourariaCarbono: AddressLike];
      export type OutputTuple = [registroOrganizacoes: string, creditoCarbonoToken: string, certificadoCompensacaoNFT: string, tesourariaCarbono: string];
      export interface OutputObject {registroOrganizacoes: string, creditoCarbonoToken: string, certificadoCompensacaoNFT: string, tesourariaCarbono: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CreditosAposentadosEvent {
      export type InputTuple = [idAposentadoria: BigNumberish, comprador: AddressLike, idLote: BigNumberish, quantidade: BigNumberish, idCertificado: BigNumberish];
      export type OutputTuple = [idAposentadoria: bigint, comprador: string, idLote: bigint, quantidade: bigint, idCertificado: bigint];
      export interface OutputObject {idAposentadoria: bigint, comprador: string, idLote: bigint, quantidade: bigint, idCertificado: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TaxaAposentadoriaAlteradaEvent {
      export type InputTuple = [novaTaxa: BigNumberish];
      export type OutputTuple = [novaTaxa: bigint];
      export interface OutputObject {novaTaxa: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface RegistroAposentadorias extends BaseContract {
    
    connect(runner?: ContractRunner | null): RegistroAposentadorias;
    waitForDeployment(): Promise<this>;

    interface: RegistroAposentadoriasInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    alterarTaxaAposentadoria: TypedContractMethod<
      [novaTaxa: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    aposentadoriaExiste: TypedContractMethod<
      [idAposentadoria: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    aposentadorias: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, bigint, bigint, string, string, bigint, bigint] & {idAposentadoria: bigint, comprador: string, idLote: bigint, quantidade: bigint, motivo: string, uriRelatorio: string, dataAposentadoria: bigint, idCertificado: bigint }],
      'view'
    >
    

    
    aposentarCreditos: TypedContractMethod<
      [idLote: BigNumberish, quantidade: BigNumberish, motivo: string, uriRelatorio: string, uriCertificado: string, ],
      [bigint],
      'payable'
    >
    

    
    atualizarContratos: TypedContractMethod<
      [enderecoRegistroOrganizacoes: AddressLike, enderecoCreditoCarbonoToken: AddressLike, enderecoCertificadoCompensacaoNFT: AddressLike, enderecoTesourariaCarbono: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    certificadoCompensacaoNFT: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    creditoCarbonoToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    registroOrganizacoes: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    taxaAposentadoria: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    tesourariaCarbono: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    totalAposentadoPorLote: TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    totalAposentadorias: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    totalCompensadoPorComprador: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'alterarTaxaAposentadoria'): TypedContractMethod<
      [novaTaxa: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'aposentadoriaExiste'): TypedContractMethod<
      [idAposentadoria: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'aposentadorias'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, bigint, bigint, string, string, bigint, bigint] & {idAposentadoria: bigint, comprador: string, idLote: bigint, quantidade: bigint, motivo: string, uriRelatorio: string, dataAposentadoria: bigint, idCertificado: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'aposentarCreditos'): TypedContractMethod<
      [idLote: BigNumberish, quantidade: BigNumberish, motivo: string, uriRelatorio: string, uriCertificado: string, ],
      [bigint],
      'payable'
    >;
getFunction(nameOrSignature: 'atualizarContratos'): TypedContractMethod<
      [enderecoRegistroOrganizacoes: AddressLike, enderecoCreditoCarbonoToken: AddressLike, enderecoCertificadoCompensacaoNFT: AddressLike, enderecoTesourariaCarbono: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'certificadoCompensacaoNFT'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'creditoCarbonoToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'registroOrganizacoes'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'taxaAposentadoria'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'tesourariaCarbono'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'totalAposentadoPorLote'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalAposentadorias'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalCompensadoPorComprador'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'ContratosAtualizados'): TypedContractEvent<ContratosAtualizadosEvent.InputTuple, ContratosAtualizadosEvent.OutputTuple, ContratosAtualizadosEvent.OutputObject>;
getEvent(key: 'CreditosAposentados'): TypedContractEvent<CreditosAposentadosEvent.InputTuple, CreditosAposentadosEvent.OutputTuple, CreditosAposentadosEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'TaxaAposentadoriaAlterada'): TypedContractEvent<TaxaAposentadoriaAlteradaEvent.InputTuple, TaxaAposentadoriaAlteradaEvent.OutputTuple, TaxaAposentadoriaAlteradaEvent.OutputObject>;

    filters: {
      
      'ContratosAtualizados(address,address,address,address)': TypedContractEvent<ContratosAtualizadosEvent.InputTuple, ContratosAtualizadosEvent.OutputTuple, ContratosAtualizadosEvent.OutputObject>;
      ContratosAtualizados: TypedContractEvent<ContratosAtualizadosEvent.InputTuple, ContratosAtualizadosEvent.OutputTuple, ContratosAtualizadosEvent.OutputObject>;
    

      'CreditosAposentados(uint256,address,uint256,uint256,uint256)': TypedContractEvent<CreditosAposentadosEvent.InputTuple, CreditosAposentadosEvent.OutputTuple, CreditosAposentadosEvent.OutputObject>;
      CreditosAposentados: TypedContractEvent<CreditosAposentadosEvent.InputTuple, CreditosAposentadosEvent.OutputTuple, CreditosAposentadosEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'TaxaAposentadoriaAlterada(uint256)': TypedContractEvent<TaxaAposentadoriaAlteradaEvent.InputTuple, TaxaAposentadoriaAlteradaEvent.OutputTuple, TaxaAposentadoriaAlteradaEvent.OutputObject>;
      TaxaAposentadoriaAlterada: TypedContractEvent<TaxaAposentadoriaAlteradaEvent.InputTuple, TaxaAposentadoriaAlteradaEvent.OutputTuple, TaxaAposentadoriaAlteradaEvent.OutputObject>;
    
    };
  }