/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface IRegistroOrganizacoesMercadoInterface extends Interface {
    getFunction(nameOrSignature: "ehComprador" | "organizacaoAtiva"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'ehComprador', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'organizacaoAtiva', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'ehComprador', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'organizacaoAtiva', data: BytesLike): Result;
  }

  

  export interface IRegistroOrganizacoesMercado extends BaseContract {
    
    connect(runner?: ContractRunner | null): IRegistroOrganizacoesMercado;
    waitForDeployment(): Promise<this>;

    interface: IRegistroOrganizacoesMercadoInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    ehComprador: TypedContractMethod<
      [carteira: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    organizacaoAtiva: TypedContractMethod<
      [carteira: AddressLike, ],
      [boolean],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'ehComprador'): TypedContractMethod<
      [carteira: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'organizacaoAtiva'): TypedContractMethod<
      [carteira: AddressLike, ],
      [boolean],
      'view'
    >;

    

    filters: {
      
    };
  }