/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface MercadoCarbonoInterface extends Interface {
    getFunction(nameOrSignature: "BASE_BPS" | "alterarTaxaMarketplace" | "atualizarContratos" | "calcularCompra" | "cancelarOferta" | "comprarCreditos" | "creditoCarbonoToken" | "criarOferta" | "ofertaDisponivel" | "ofertas" | "owner" | "registroOrganizacoes" | "renounceOwnership" | "taxaMarketplaceBps" | "tesourariaCarbono" | "totalOfertas" | "transferOwnership"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ContratosAtualizados" | "CreditosComprados" | "OfertaCancelada" | "OfertaCriada" | "OwnershipTransferred" | "TaxaMarketplaceAlterada"): EventFragment;

    encodeFunctionData(functionFragment: 'BASE_BPS', values?: undefined): string;
encodeFunctionData(functionFragment: 'alterarTaxaMarketplace', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'atualizarContratos', values: [AddressLike, AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'calcularCompra', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'cancelarOferta', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'comprarCreditos', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'creditoCarbonoToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'criarOferta', values: [BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'ofertaDisponivel', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'ofertas', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'registroOrganizacoes', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'taxaMarketplaceBps', values?: undefined): string;
encodeFunctionData(functionFragment: 'tesourariaCarbono', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalOfertas', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'BASE_BPS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'alterarTaxaMarketplace', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'atualizarContratos', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'calcularCompra', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cancelarOferta', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'comprarCreditos', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'creditoCarbonoToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'criarOferta', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ofertaDisponivel', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ofertas', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registroOrganizacoes', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'taxaMarketplaceBps', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tesourariaCarbono', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalOfertas', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
  }

  
    export namespace ContratosAtualizadosEvent {
      export type InputTuple = [creditoCarbonoToken: AddressLike, registroOrganizacoes: AddressLike, tesourariaCarbono: AddressLike];
      export type OutputTuple = [creditoCarbonoToken: string, registroOrganizacoes: string, tesourariaCarbono: string];
      export interface OutputObject {creditoCarbonoToken: string, registroOrganizacoes: string, tesourariaCarbono: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CreditosCompradosEvent {
      export type InputTuple = [idOferta: BigNumberish, comprador: AddressLike, vendedor: AddressLike, idLote: BigNumberish, quantidade: BigNumberish, valorTotal: BigNumberish, valorTaxa: BigNumberish, valorVendedor: BigNumberish];
      export type OutputTuple = [idOferta: bigint, comprador: string, vendedor: string, idLote: bigint, quantidade: bigint, valorTotal: bigint, valorTaxa: bigint, valorVendedor: bigint];
      export interface OutputObject {idOferta: bigint, comprador: string, vendedor: string, idLote: bigint, quantidade: bigint, valorTotal: bigint, valorTaxa: bigint, valorVendedor: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OfertaCanceladaEvent {
      export type InputTuple = [idOferta: BigNumberish, vendedor: AddressLike];
      export type OutputTuple = [idOferta: bigint, vendedor: string];
      export interface OutputObject {idOferta: bigint, vendedor: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OfertaCriadaEvent {
      export type InputTuple = [idOferta: BigNumberish, vendedor: AddressLike, idLote: BigNumberish, quantidade: BigNumberish, precoPorCredito: BigNumberish];
      export type OutputTuple = [idOferta: bigint, vendedor: string, idLote: bigint, quantidade: bigint, precoPorCredito: bigint];
      export interface OutputObject {idOferta: bigint, vendedor: string, idLote: bigint, quantidade: bigint, precoPorCredito: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TaxaMarketplaceAlteradaEvent {
      export type InputTuple = [novaTaxaBps: BigNumberish];
      export type OutputTuple = [novaTaxaBps: bigint];
      export interface OutputObject {novaTaxaBps: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface MercadoCarbono extends BaseContract {
    
    connect(runner?: ContractRunner | null): MercadoCarbono;
    waitForDeployment(): Promise<this>;

    interface: MercadoCarbonoInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    BASE_BPS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    alterarTaxaMarketplace: TypedContractMethod<
      [novaTaxaBps: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    atualizarContratos: TypedContractMethod<
      [enderecoCreditoCarbonoToken: AddressLike, enderecoRegistroOrganizacoes: AddressLike, enderecoTesourariaCarbono: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    calcularCompra: TypedContractMethod<
      [idOferta: BigNumberish, quantidade: BigNumberish, ],
      [[bigint, bigint, bigint] & {valorTotal: bigint, valorTaxa: bigint, valorVendedor: bigint }],
      'view'
    >
    

    
    cancelarOferta: TypedContractMethod<
      [idOferta: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    comprarCreditos: TypedContractMethod<
      [idOferta: BigNumberish, quantidade: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    creditoCarbonoToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    criarOferta: TypedContractMethod<
      [idLote: BigNumberish, quantidade: BigNumberish, precoPorCredito: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    ofertaDisponivel: TypedContractMethod<
      [idOferta: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    ofertas: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, bigint, bigint, bigint, bigint, bigint, bigint, bigint] & {idOferta: bigint, vendedor: string, idLote: bigint, quantidadeTotal: bigint, quantidadeDisponivel: bigint, precoPorCredito: bigint, estadoOferta: bigint, dataCriacao: bigint, dataAtualizacao: bigint }],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    registroOrganizacoes: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    taxaMarketplaceBps: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    tesourariaCarbono: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    totalOfertas: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'BASE_BPS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'alterarTaxaMarketplace'): TypedContractMethod<
      [novaTaxaBps: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'atualizarContratos'): TypedContractMethod<
      [enderecoCreditoCarbonoToken: AddressLike, enderecoRegistroOrganizacoes: AddressLike, enderecoTesourariaCarbono: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'calcularCompra'): TypedContractMethod<
      [idOferta: BigNumberish, quantidade: BigNumberish, ],
      [[bigint, bigint, bigint] & {valorTotal: bigint, valorTaxa: bigint, valorVendedor: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'cancelarOferta'): TypedContractMethod<
      [idOferta: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'comprarCreditos'): TypedContractMethod<
      [idOferta: BigNumberish, quantidade: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'creditoCarbonoToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'criarOferta'): TypedContractMethod<
      [idLote: BigNumberish, quantidade: BigNumberish, precoPorCredito: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'ofertaDisponivel'): TypedContractMethod<
      [idOferta: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'ofertas'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, bigint, bigint, bigint, bigint, bigint, bigint, bigint] & {idOferta: bigint, vendedor: string, idLote: bigint, quantidadeTotal: bigint, quantidadeDisponivel: bigint, precoPorCredito: bigint, estadoOferta: bigint, dataCriacao: bigint, dataAtualizacao: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'registroOrganizacoes'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'taxaMarketplaceBps'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'tesourariaCarbono'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'totalOfertas'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'ContratosAtualizados'): TypedContractEvent<ContratosAtualizadosEvent.InputTuple, ContratosAtualizadosEvent.OutputTuple, ContratosAtualizadosEvent.OutputObject>;
getEvent(key: 'CreditosComprados'): TypedContractEvent<CreditosCompradosEvent.InputTuple, CreditosCompradosEvent.OutputTuple, CreditosCompradosEvent.OutputObject>;
getEvent(key: 'OfertaCancelada'): TypedContractEvent<OfertaCanceladaEvent.InputTuple, OfertaCanceladaEvent.OutputTuple, OfertaCanceladaEvent.OutputObject>;
getEvent(key: 'OfertaCriada'): TypedContractEvent<OfertaCriadaEvent.InputTuple, OfertaCriadaEvent.OutputTuple, OfertaCriadaEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'TaxaMarketplaceAlterada'): TypedContractEvent<TaxaMarketplaceAlteradaEvent.InputTuple, TaxaMarketplaceAlteradaEvent.OutputTuple, TaxaMarketplaceAlteradaEvent.OutputObject>;

    filters: {
      
      'ContratosAtualizados(address,address,address)': TypedContractEvent<ContratosAtualizadosEvent.InputTuple, ContratosAtualizadosEvent.OutputTuple, ContratosAtualizadosEvent.OutputObject>;
      ContratosAtualizados: TypedContractEvent<ContratosAtualizadosEvent.InputTuple, ContratosAtualizadosEvent.OutputTuple, ContratosAtualizadosEvent.OutputObject>;
    

      'CreditosComprados(uint256,address,address,uint256,uint256,uint256,uint256,uint256)': TypedContractEvent<CreditosCompradosEvent.InputTuple, CreditosCompradosEvent.OutputTuple, CreditosCompradosEvent.OutputObject>;
      CreditosComprados: TypedContractEvent<CreditosCompradosEvent.InputTuple, CreditosCompradosEvent.OutputTuple, CreditosCompradosEvent.OutputObject>;
    

      'OfertaCancelada(uint256,address)': TypedContractEvent<OfertaCanceladaEvent.InputTuple, OfertaCanceladaEvent.OutputTuple, OfertaCanceladaEvent.OutputObject>;
      OfertaCancelada: TypedContractEvent<OfertaCanceladaEvent.InputTuple, OfertaCanceladaEvent.OutputTuple, OfertaCanceladaEvent.OutputObject>;
    

      'OfertaCriada(uint256,address,uint256,uint256,uint256)': TypedContractEvent<OfertaCriadaEvent.InputTuple, OfertaCriadaEvent.OutputTuple, OfertaCriadaEvent.OutputObject>;
      OfertaCriada: TypedContractEvent<OfertaCriadaEvent.InputTuple, OfertaCriadaEvent.OutputTuple, OfertaCriadaEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'TaxaMarketplaceAlterada(uint256)': TypedContractEvent<TaxaMarketplaceAlteradaEvent.InputTuple, TaxaMarketplaceAlteradaEvent.OutputTuple, TaxaMarketplaceAlteradaEvent.OutputObject>;
      TaxaMarketplaceAlterada: TypedContractEvent<TaxaMarketplaceAlteradaEvent.InputTuple, TaxaMarketplaceAlteradaEvent.OutputTuple, TaxaMarketplaceAlteradaEvent.OutputObject>;
    
    };
  }