/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { AdaptadorOraculoChainlink__factory } from './AdaptadorOraculoChainlink__factory.js';
export { AggregatorV3Interface__factory } from './AggregatorV3Interface__factory.js';