/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IRegistroProjetosCarbonoValidacao, IRegistroProjetosCarbonoValidacaoInterface } from "../../ValidacaoProjetos.sol/IRegistroProjetosCarbonoValidacao.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "idProjeto",
        "type": "uint256"
      }
    ],
    "name": "marcarEmVotacao",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "idProjeto",
        "type": "uint256"
      }
    ],
    "name": "obterCreditosSolicitados",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "idProjeto",
        "type": "uint256"
      },
      {
        "internalType": "bool",
        "name": "aprovado",
        "type": "bool"
      },
      {
        "internalType": "uint256",
        "name": "creditosAprovados",
        "type": "uint256"
      }
    ],
    "name": "registrarResultadoValidacao",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class IRegistroProjetosCarbonoValidacao__factory {
    static readonly abi = _abi;
    static createInterface(): IRegistroProjetosCarbonoValidacaoInterface {
      return new Interface(_abi) as IRegistroProjetosCarbonoValidacaoInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IRegistroProjetosCarbonoValidacao {
      return new Contract(address, _abi, runner) as unknown as IRegistroProjetosCarbonoValidacao;
    }
  }
  