/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IStakingCarbonoValidacao, IStakingCarbonoValidacaoInterface } from "../../ValidacaoProjetos.sol/IStakingCarbonoValidacao.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "participante",
        "type": "address"
      }
    ],
    "name": "saldoEmStake",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class IStakingCarbonoValidacao__factory {
    static readonly abi = _abi;
    static createInterface(): IStakingCarbonoValidacaoInterface {
      return new Interface(_abi) as IStakingCarbonoValidacaoInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IStakingCarbonoValidacao {
      return new Contract(address, _abi, runner) as unknown as IStakingCarbonoValidacao;
    }
  }
  